#!/usr/bin/env python3
"""
Charging Station — the DDS approach: Pure DDS (Data-Centric Everything)

Manages a single charging dock for the robot fleet.  Only one robot can
charge at a time; additional robots queue up in FIFO order and wait near
the station until the dock becomes free.

Multiple stations can run simultaneously (e.g. one at each corner of the
arena) to provide redundancy and reduce wait times.

DDS architecture:
  • Two rti.rpc.SimpleReplier objects handle slot negotiation
    (callback-driven — no application threads needed):
    - SlotReserve → SlotAssignment  (service: "ChargingSlotReserve")
    - SlotRelease → SlotReleaseAck         (service: "ChargingSlotRelease")
  • StationStatus (pub-sub, RELIABLE / TRANSIENT_LOCAL) publishes queue
    length and dock coordinates.  Robots pick the best station locally
    and send a single directed SlotReserve.
  • Queue monitoring is pub-sub driven: robots watch StationStatus
    for rank changes.
  • DDS SPDP handles discovery — no application-level discovery code.
  • rti.rpc correlates via SampleIdentity (writer GUID + sequence number).
  • SimpleReplier dispatches request callbacks on DDS internal threads.

See charging_station_spec.md for the full specification.
"""

import rti.connextdds as dds
import rti.rpc as rpc
import time
import argparse
import uuid
import os
from datetime import datetime
from collections import OrderedDict
from typing import Dict, Optional
from threading import Lock

# Types generated by:  rtiddsgen -language python robot_types.idl
from robot_types import (
    SlotReserve, SlotAssignment, SlotRelease, SlotReleaseAck,
    StationStatus, QueueEntry,
)


# ═════════════════════════════════════════════════════════════════════════════
# Constants
# ═════════════════════════════════════════════════════════════════════════════

# Conservative estimate for wait-time calculations.  In the simulation,
# charging refills at ~2 %/s so a full recharge from 0 takes ~50 s.
CHARGE_DURATION_ESTIMATE = 45


# ═════════════════════════════════════════════════════════════════════════════
# Compact log timestamp
# ═════════════════════════════════════════════════════════════════════════════

def _ts():
    """Return a compact HH:MM:SS timestamp for log lines."""
    return datetime.now().strftime("%H:%M:%S")


# ═════════════════════════════════════════════════════════════════════════════
# ChargingStation — Pure DDS charging dock manager
# ═════════════════════════════════════════════════════════════════════════════

class ChargingStation:
    """Manages a single-dock charging station with a FIFO queue.

    Queue state:
        _queue:    OrderedDict  slot_id → {"robot_id": str, "ts": float}
        _charging: slot_id or None  (the robot currently on the dock)

    DDS entities:
        1 StationStatus writer (pub-sub)
        2 rti.rpc.SimpleReplier objects (slot negotiation, callback-driven)

    Threads:
        1 main (blocks on sleep loop)
        0 app threads — SimpleReplier dispatches on DDS internal threads
    """

    def __init__(self, station_id: str, domain_id: int = 0,
                 dock_x: float = 50.0, dock_y: float = 5.0):
        self.station_id = station_id
        self.domain_id = domain_id
        self.dock_x = dock_x
        self.dock_y = dock_y
        self.running = False

        # ── Queue state (protected by self.lock) ──────────────────────────
        self._queue: OrderedDict = OrderedDict()
        self._charging: Optional[str] = None   # slot_id on the dock
        self.lock = Lock()

        # ── DDS entities ──────────────────────────────────────────────────
        self.participant: Optional[dds.DomainParticipant] = None
        self.writers: Dict[str, dds.DataWriter] = {}

        # ── RPC entities (rti.rpc.SimpleReplier) ─────────────────────────
        self.reserve_replier: Optional[rpc.SimpleReplier] = None
        self.release_replier: Optional[rpc.SimpleReplier] = None

    # ═════════════════════════════════════════════════════════════════════
    # DDS Initialisation
    # ═════════════════════════════════════════════════════════════════════

    def initialize_dds(self):
        """Create the DDS DomainParticipant, StationStatus writer, and 2 SimpleRepliers.

        QoS profiles are loaded from robot_qos.xml (Pattern-based).
        Types are generated by rtiddsgen from robot_types.idl.
        SimpleReplier dispatches requests on DDS internal threads via
        callback handlers — no application threads required.
        """
        print(f"[{self.station_id} {_ts()}] Initializing DDS on domain {self.domain_id}...")

        # Resolve the path to robot_qos.xml relative to this script
        script_dir = os.path.dirname(os.path.abspath(__file__))
        qos_xml = os.path.join(script_dir, "robot_qos.xml")
        qos_provider = dds.QosProvider(qos_xml)

        self.participant = dds.DomainParticipant(self.domain_id)

        # ── Pub-Sub: StationStatus topic ──────────────────────────────────
        status_topic = dds.Topic(self.participant, "StationStatus", StationStatus)
        publisher = dds.Publisher(self.participant)

        status_w_qos = qos_provider.datawriter_qos_from_profile(
            "RobotQosLibrary::StationStatusProfile")
        self.writers['station_status'] = dds.DataWriter(
            publisher, status_topic, status_w_qos)

        # ── RPC: Slot Negotiation SimpleRepliers ──────────────────────────
        # SimpleReplier dispatches on DDS internal threads: one callback
        # per request, return value is the reply.  Service names must
        # match the Requesters in robot_node.py.
        self.reserve_replier = rpc.SimpleReplier(
            request_type=SlotReserve,
            reply_type=SlotAssignment,
            participant=self.participant,
            service_name="ChargingSlotReserve",
            handler=self._on_slot_reserve,
        )
        self.release_replier = rpc.SimpleReplier(
            request_type=SlotRelease,
            reply_type=SlotReleaseAck,
            participant=self.participant,
            service_name="ChargingSlotRelease",
            handler=self._on_slot_release,
        )

        print(f"[{self.station_id} {_ts()}] DDS initialized — "
              f"1 StationStatus writer + 2 SimpleRepliers")

    # ═════════════════════════════════════════════════════════════════════
    # SimpleReplier Handlers (dispatched on DDS internal threads)
    # ═════════════════════════════════════════════════════════════════════

    def _on_slot_reserve(self, request: SlotReserve) -> SlotAssignment:
        """Handle a SlotReserve and publish updated status."""
        assignment = self._handle_slot_reserve(request)
        self._publish_status()
        return assignment

    def _on_slot_release(self, request: SlotRelease) -> SlotReleaseAck:
        """Handle a SlotRelease and publish updated status."""
        ack = self._handle_slot_release(request)
        self._publish_status()
        return ack

    # ═════════════════════════════════════════════════════════════════════
    # Slot Reserve Handling
    # ═════════════════════════════════════════════════════════════════════

    def _handle_slot_reserve(self, request: SlotReserve) -> SlotAssignment:
        """Reserve a queue slot and return a SlotAssignment.

        Every SlotReserve is immediately confirmed — the entry goes
        straight into the FIFO queue.

        If the robot targets a different station, return not-granted
        so that fan-out replies don't create phantom entries.
        """
        with self.lock:
            # Ignore reserves targeted at a different station (fan-out)
            if request.station_id and request.station_id != self.station_id:
                return SlotAssignment(
                    station_id=self.station_id,
                    slot_id="",
                    granted=False,
                    queue_rank=-1,
                    dock_x=self.dock_x,
                    dock_y=self.dock_y,
                )

            slot_id = str(uuid.uuid4())[:8]
            rank = len(self._queue)

            self._queue[slot_id] = {
                "robot_id": request.robot_id,
                "ts": time.time(),
            }

            # If first in line and dock is free → dock immediately
            if rank == 0 and self._charging is None:
                self._charging = slot_id
                print(f"[{self.station_id} {_ts()}] {request.robot_id} "
                      f"→ DOCKING (slot {slot_id})")
                return SlotAssignment(
                    station_id=self.station_id,
                    slot_id=slot_id,
                    granted=True,
                    queue_rank=0,
                    dock_x=self.dock_x,
                    dock_y=self.dock_y,
                )

            print(f"[{self.station_id} {_ts()}] {request.robot_id} "
                  f"reserved slot {slot_id} rank={rank} "
                  f"(batt={request.battery_level:.0f}%)")
            return SlotAssignment(
                station_id=self.station_id,
                slot_id=slot_id,
                granted=True,
                queue_rank=rank,
                dock_x=self.dock_x,
                dock_y=self.dock_y,
            )

    # ═════════════════════════════════════════════════════════════════════
    # Slot Release Handling
    # ═════════════════════════════════════════════════════════════════════

    def _handle_slot_release(self, request: SlotRelease) -> SlotReleaseAck:
        """Robot finished charging — free the dock and advance the queue."""
        with self.lock:
            # Ignore releases targeted at a different station (fan-out)
            if request.station_id and request.station_id != self.station_id:
                return SlotReleaseAck(
                    station_id=self.station_id,
                    slot_id=request.slot_id,
                    success=True,
                )

            info = self._queue.get(request.slot_id)
            if not info:
                # Idempotent: slot already removed or never existed
                return SlotReleaseAck(
                    station_id=self.station_id,
                    slot_id=request.slot_id,
                    success=True,
                )

            rid = info["robot_id"]
            del self._queue[request.slot_id]

            if self._charging == request.slot_id:
                self._charging = None
                print(f"[{self.station_id} {_ts()}] {rid} released dock "
                      f"(slot {request.slot_id})")
                # Advance: next confirmed robot gets the dock
                self._advance_queue()
            else:
                print(f"[{self.station_id} {_ts()}] {rid} released waiting "
                      f"slot {request.slot_id}")

            return SlotReleaseAck(
                station_id=self.station_id,
                slot_id=request.slot_id,
                success=True,
            )

    # ═════════════════════════════════════════════════════════════════════
    # StationStatus Publishing
    # ═════════════════════════════════════════════════════════════════════

    def _publish_status(self):
        """Publish a StationStatus sample with current queue state."""
        with self.lock:
            docked_robot = ""
            if self._charging:
                info = self._queue.get(self._charging)
                if info:
                    docked_robot = info["robot_id"]
                else:
                    # Queue entry vanished but _charging wasn't cleared
                    # — defensive cleanup so the UI doesn't show a ghost.
                    print(f"[{self.station_id} {_ts()}] ⚠ _charging={self._charging} "
                          f"has no queue entry — clearing")
                    self._charging = None

            entries = []
            for rank, (sid, info) in enumerate(self._queue.items()):
                entries.append(QueueEntry(
                    robot_id=info["robot_id"],
                    rank=rank,
                    confirmed=True,
                ))

            status = StationStatus(
                station_id=self.station_id,
                dock_x=self.dock_x,
                dock_y=self.dock_y,
                is_occupied=(self._charging is not None),
                docked_robot_id=docked_robot,
                queue=entries,
            )

        self.writers['station_status'].write(status)

    # ═════════════════════════════════════════════════════════════════════
    # Queue Helpers
    # ═════════════════════════════════════════════════════════════════════

    def _queue_rank(self, slot_id: str) -> int:
        """Return 0-based rank in the queue (-1 if not found).
        Must be called with self.lock held."""
        for i, sid in enumerate(self._queue):
            if sid == slot_id:
                return i
        return -1

    def _advance_queue(self):
        """Promote the next robot in the queue to the dock.

        The promoted robot learns of its new rank via the StationStatus
        publication that follows immediately.

        Must be called with self.lock held.
        """
        for sid, info in self._queue.items():
            self._charging = sid
            print(f"[{self.station_id} {_ts()}] {info['robot_id']} "
                  f"→ DOCKING (advanced, slot {sid})")
            return
        print(f"[{self.station_id} {_ts()}] Dock free — queue empty")

    # ═════════════════════════════════════════════════════════════════════
    # Run
    # ═════════════════════════════════════════════════════════════════════

    def run(self):
        """Initialise DDS, block until Ctrl-C.

        SimpleReplier callbacks handle requests on DDS internal threads,
        so no application threads are needed.
        """
        self.initialize_dds()
        self.running = True

        # Publish initial (empty) status
        self._publish_status()

        print(f"[{self.station_id} {_ts()}] ⚡ Charging station running "
              f"(0 app threads — SimpleReplier callbacks on DDS threads)")
        print(f"[{self.station_id} {_ts()}]   Dock at "
              f"({self.dock_x}, {self.dock_y})")
        print(f"[{self.station_id} {_ts()}] Press Ctrl+C to stop.")

        try:
            while self.running:
                time.sleep(1)
        except KeyboardInterrupt:
            pass
        finally:
            self.shutdown()

    def shutdown(self):
        """Clean shutdown: close DDS (SimpleReplier callbacks stop automatically)."""
        print(f"\n[{self.station_id} {_ts()}] Shutting down…")
        self.running = False
        if self.participant:
            self.participant.close()
            self.participant = None
        print(f"[{self.station_id} {_ts()}] Goodbye.")


# ═════════════════════════════════════════════════════════════════════════════
# main
# ═════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="Charging Station — Pure DDS (the DDS approach)")
    parser.add_argument("--id", required=True, dest="station_id",
                        help="Station identifier (e.g. station1)")
    parser.add_argument("--domain", type=int, default=0,
                        help="DDS Domain ID (must match robot nodes)")
    parser.add_argument("--dock-x", type=float, default=50.0,
                        help="Dock X coordinate in the arena (0–100)")
    parser.add_argument("--dock-y", type=float, default=5.0,
                        help="Dock Y coordinate in the arena (0–100)")
    args = parser.parse_args()

    station = ChargingStation(
        station_id=args.station_id,
        domain_id=args.domain,
        dock_x=args.dock_x,
        dock_y=args.dock_y,
    )
    station.run()


if __name__ == "__main__":
    main()
