#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Real-Time Innovations, Inc.
# SPDX-License-Identifier: Apache-2.0
"""
Robot Fleet UI – the DDS approach: Pure DDS (Connext)

A live web dashboard that subscribes to a fleet of robot nodes and
charging stations via DDS, displays real-time Kinematic State, Operational
State, Intent, Telemetry, and Charging Station status, and lets the
operator send commands to individual robots.

Architecture:
    FleetStateStore  – transport-agnostic data store (same concept as the gRPC approach)
    DdsFleetClient   – DDS communication layer; 6 DataReaders + 1 Requester
    Flask / HTML / JS – presentation layer; reads store via SSE, sends commands
                        through the client

Key differences from the gRPC approach:
  • No gRPC, no Zeroconf, no per-robot connections, no reconnect loops.
  • 6 DataReaders total (one per topic type) — flat regardless of fleet size.
  • 1 rti.rpc.Requester for commands — fan-out is automatic.
  • DDS SPDP replaces mDNS discovery — zero CLI flags needed.
  • ~4 threads total vs ~22 in the gRPC approach for a 3-robot fleet.

Usage:
    python robot_ui.py [--domain 0] --ui-port 5000
"""

import rti.connextdds as dds
import rti.rpc as rpc
import os
import threading
import time
import json
import argparse
from typing import Dict, Optional, List

from flask import Flask, Response, render_template_string, request, jsonify, send_from_directory

# Types generated by:  rtiddsgen -language python robot_types.idl
from robot_types import (
    RobotStatus, RobotIntentType, Command,
    KinematicState, OperationalState, Intent, Telemetry, VideoFrame,
    StationStatus, CoveragePoint,
    CommandRequest, CommandResponse,
    GotoParameters, SetPathParameters, Waypoint,
)


# ─────────────────────────────────────────────────────────────────────────────
# Fleet State Store – transport-agnostic, thread-safe data store
# ─────────────────────────────────────────────────────────────────────────────
class FleetStateStore:
    """Thread-safe store for fleet state, intent, telemetry, and charging info.

    This class has **no knowledge** of DDS, protobuf, or any transport.
    It holds plain Python dicts and provides a snapshot for the UI layer.
    """

    def __init__(self, domain_id: int = 0):
        self.lock = threading.Lock()
        self.kinematic: Dict[str, dict] = {}      # robot_id → {x, y, z, vx, vy, vz, heading, ts}
        self.operational: Dict[str, dict] = {}     # robot_id → {status, battery, ts}
        self.intent: Dict[str, dict] = {}          # robot_id → {type, target_x, target_y, ts, ...}
        self.telemetry: Dict[str, dict] = {}       # robot_id → {cpu, memory, temperature, signal_strength, ts}
        self.charging: Dict[str, dict] = {}        # station_id → {station_id, dock_robot, queue, dock_x, dock_y}
        self.coverage: Dict[str, list] = {}        # robot_id → [{x, y, seq}, …] (sorted by seq)
        self.domain_id = domain_id

    # ── reads ──────────────────────────────────────────────────────────────

    def snapshot(self) -> dict:
        """Return a JSON-serialisable copy of all data stores."""
        with self.lock:
            # Build merged state for the map (position + status + velocity)
            merged: Dict[str, dict] = {}
            for rid, kd in self.kinematic.items():
                merged[rid] = dict(kd)
            for rid, od in self.operational.items():
                if rid in merged:
                    merged[rid].update(od)
                else:
                    merged[rid] = dict(od)
            return {
                "state": merged,
                "kinematic": {k: dict(v) for k, v in self.kinematic.items()},
                "operational": {k: dict(v) for k, v in self.operational.items()},
                "intent": dict(self.intent),
                "telemetry": dict(self.telemetry),
                "charging": {k: dict(v) for k, v in self.charging.items()},
                "coverage": {k: list(v) for k, v in self.coverage.items()},
                "domain_id": self.domain_id,
            }

    def known_robots(self) -> List[str]:
        """Return sorted list of robot_ids that have kinematic data."""
        with self.lock:
            return sorted(self.kinematic.keys())

    # ── writes (called by the DDS client) ─────────────────────────────────

    def update_kinematic(self, robot_id: str, data: dict):
        """Store a kinematic state update."""
        with self.lock:
            self.kinematic[robot_id] = data

    def update_operational(self, robot_id: str, data: dict):
        """Store an operational state update."""
        with self.lock:
            self.operational[robot_id] = data

    def update_intent(self, robot_id: str, data: dict):
        """Store an intent update."""
        with self.lock:
            self.intent[robot_id] = data

    def update_telemetry(self, robot_id: str, data: dict):
        """Store a telemetry update."""
        with self.lock:
            self.telemetry[robot_id] = data

    def update_charging(self, station_id: str, data: dict):
        """Store a charging station status update."""
        with self.lock:
            self.charging[station_id] = data

    def update_coverage(self, robot_id: str, x: float, y: float):
        """Append a coverage point (from CoveragePoint DDS topic)."""
        with self.lock:
            if robot_id not in self.coverage:
                self.coverage[robot_id] = []
            self.coverage[robot_id].append({"x": x, "y": y})

    def clear_coverage(self):
        """Clear all accumulated coverage data."""
        with self.lock:
            self.coverage.clear()

    def remove_robot(self, robot_id: str):
        """Remove all data for a robot (liveliness lost)."""
        with self.lock:
            self.kinematic.pop(robot_id, None)
            self.operational.pop(robot_id, None)
            self.intent.pop(robot_id, None)
            self.telemetry.pop(robot_id, None)


# ─────────────────────────────────────────────────────────────────────────────
# DDS Fleet Client – all DDS / transport logic lives here
# ─────────────────────────────────────────────────────────────────────────────
class DdsFleetClient:
    """Owns the DDS DomainParticipant and all DDS entities.

    Creates 6 DataReaders (one per topic type) that receive data from
    ALL robots and stations simultaneously — no per-robot connections.
    Uses rti.rpc.Requester for sending commands.
    """

    def __init__(self, store: FleetStateStore, domain_id: int = 0):
        self.store = store
        self.domain_id = domain_id
        self.running = True
        self.participant: Optional[dds.DomainParticipant] = None
        self.command_requester: Optional[rpc.Requester] = None
        # Video frame buffer: robot_id → latest JPEG bytes
        self._video_frames: Dict[str, bytes] = {}
        self._video_lock = threading.Lock()
        # ── Video reader (partition-based matching) ──
        self._video_reader: Optional[dds.DataReader] = None
        self._video_subscriber: Optional[dds.Subscriber] = None
        self._active_video_robot: Optional[str] = None
        self._video_generation: int = 0  # bumped on each select/deselect

    def stop(self):
        self.running = False

    # ── DDS initialisation ─────────────────────────────────────────────────

    def start(self):
        """Create the DDS participant, readers, listeners, and requester."""
        print(f"[ui] Initializing DDS on domain {self.domain_id}...")

        # Resolve robot_qos.xml relative to this script
        script_dir = os.path.dirname(os.path.abspath(__file__))
        qos_xml = os.path.join(script_dir, "robot_qos.xml")
        qos_provider = dds.QosProvider(qos_xml)

        self.participant = dds.DomainParticipant(self.domain_id)

        # ── Topics ────────────────────────────────────────────────────────
        kin_topic     = dds.Topic(self.participant, "KinematicState",   KinematicState)
        op_topic      = dds.Topic(self.participant, "OperationalState", OperationalState)
        intent_topic  = dds.Topic(self.participant, "Intent",           Intent)
        telem_topic   = dds.Topic(self.participant, "Telemetry",        Telemetry)
        video_topic   = dds.Topic(self.participant, "VideoFrame",       VideoFrame)
        station_topic = dds.Topic(self.participant, "StationStatus",    StationStatus)
        cov_topic     = dds.Topic(self.participant, "CoveragePoint",   CoveragePoint)

        subscriber = dds.Subscriber(self.participant)

        # ── DataReaders with QoS from profiles ────────────────────────────
        kin_r_qos = qos_provider.datareader_qos_from_profile(
            "RobotQosLibrary::KinematicStateProfile")
        op_r_qos = qos_provider.datareader_qos_from_profile(
            "RobotQosLibrary::OperationalStateProfile")
        intent_r_qos = qos_provider.datareader_qos_from_profile(
            "RobotQosLibrary::IntentProfile")
        telem_r_qos = qos_provider.datareader_qos_from_profile(
            "RobotQosLibrary::TelemetryProfile")
        video_r_qos = qos_provider.datareader_qos_from_profile(
            "RobotQosLibrary::VideoProfile")
        station_r_qos = qos_provider.datareader_qos_from_profile(
            "RobotQosLibrary::StationStatusProfile")
        cov_r_qos = qos_provider.datareader_qos_from_profile(
            "RobotQosLibrary::CoverageProfile")

        self._kin_reader     = dds.DataReader(subscriber, kin_topic,     kin_r_qos)
        self._op_reader      = dds.DataReader(subscriber, op_topic,      op_r_qos)
        self._intent_reader  = dds.DataReader(subscriber, intent_topic,  intent_r_qos)
        self._telem_reader   = dds.DataReader(subscriber, telem_topic,   telem_r_qos)
        self._station_reader = dds.DataReader(subscriber, station_topic, station_r_qos)
        self._cov_reader     = dds.DataReader(subscriber, cov_topic,     cov_r_qos)

        # ── Video reader: partition-based matching ─────────────────────
        # Each robot's VideoFrame DataWriter sits on a Publisher whose
        # partition is the robot's own ID (e.g. 'tractor_1').
        #
        # The UI creates a dedicated Subscriber for video whose partition
        # starts as '__NONE__' (matches nothing).  When the operator
        # selects a robot, we change the Subscriber partition to that
        # robot_id → DDS matches the writer/reader pair.  When the
        # operator stops, partition reverts to '__NONE__' → unmatch.
        #
        # Advantages over CFT + propagated PropertyQos:
        #   • No filter evaluation per sample — matching is at the
        #     partition level (most efficient DDS mechanism).
        #   • Partition changes trigger publication_matched_status on the
        #     writer side — fully event-driven, no polling needed.
        #   • Simpler: one QoS knob (partition) instead of two (CFT +
        #     propagated property).
        _VIDEO_SENTINEL = "__NONE__"
        video_sub_qos = dds.SubscriberQos()
        video_sub_qos.partition.name = [_VIDEO_SENTINEL]
        self._video_subscriber = dds.Subscriber(
            self.participant, video_sub_qos)
        self._video_reader = dds.DataReader(
            self._video_subscriber, video_topic, video_r_qos)

        # ── Polling thread for all readers ────────────────────────────────
        # We use a single polling thread instead of DataReaderListeners
        # because DDS listener callbacks hold an internal lock that can
        # complicate shutdown.  Polling at ~20 Hz is simpler and sufficient
        # for a 5 Hz SSE dashboard.
        threading.Thread(target=self._poll_readers, daemon=True).start()

        # ── Command Requester (rti.rpc) ───────────────────────────────────
        self.command_requester = rpc.Requester(
            request_type=CommandRequest,
            reply_type=CommandResponse,
            participant=self.participant,
            service_name="RobotCommand",
        )

        n_readers = 7
        print(f"[ui] DDS initialized — {n_readers} DataReaders + 1 Requester"
              f" (video via partition-based matching)")

    # ── Reader polling ─────────────────────────────────────────────────────

    def _poll_readers(self):
        """Poll all 7 DataReaders at ~20 Hz and push data into the store."""
        while self.running:
            try:
                self._poll_kinematic()
                self._poll_operational()
                self._poll_intent()
                self._poll_telemetry()
                self._poll_video()
                self._poll_station()
                self._poll_coverage()
            except Exception as e:
                print(f"[ui] poll error: {e}")
            time.sleep(0.05)  # 20 Hz

    def _poll_kinematic(self):
        for sample in self._kin_reader.take():
            if sample.info.valid:
                d = sample.data
                self.store.update_kinematic(d.robot_id, {
                    "x": d.position.x, "y": d.position.y, "z": d.position.z,
                    "vx": d.velocity.x, "vy": d.velocity.y, "vz": d.velocity.z,
                    "heading": d.heading,
                    "ts": time.time(),
                })

    def _poll_operational(self):
        for sample in self._op_reader.take():
            if sample.info.valid:
                d = sample.data
                self.store.update_operational(d.robot_id, {
                    "status": d.status.name,
                    "battery": d.battery_level,
                    "ts": time.time(),
                })

    def _poll_intent(self):
        for sample in self._intent_reader.take():
            if sample.info.valid:
                d = sample.data
                entry = {
                    "type": d.intent_type.name,
                    "target_x": d.target_position.x,
                    "target_y": d.target_position.y,
                    "ts": time.time(),
                }
                if d.path_waypoints:
                    entry["waypoints"] = [
                        {"x": wp.x, "y": wp.y} for wp in d.path_waypoints
                    ]
                    entry["waypoint_index"] = d.path_index
                self.store.update_intent(d.robot_id, entry)

    def _poll_telemetry(self):
        for sample in self._telem_reader.take():
            if sample.info.valid:
                d = sample.data
                self.store.update_telemetry(d.robot_id, {
                    "cpu": d.cpu_usage,
                    "memory": d.memory_usage,
                    "temperature": d.temperature,
                    "signal_strength": d.signal_strength,
                    "ts": time.time(),
                })

    def _poll_video(self):
        for sample in self._video_reader.take():
            if sample.info.valid:
                d = sample.data
                with self._video_lock:
                    self._video_frames[d.robot_id] = bytes(d.frame_data)
                # Periodic frame-arrival log (every 25th frame)
                key = f'_vid_rx_{d.robot_id}'
                n = getattr(self, key, 0) + 1
                setattr(self, key, n)
                if n % 25 == 0:
                    print(f"[ui] 📷 poll_video: {n} frames received from {d.robot_id}")

    def _poll_station(self):
        for sample in self._station_reader.take():
            if sample.info.valid:
                d = sample.data
                queue = [
                    {"robot_id": e.robot_id, "rank": e.rank, "confirmed": e.confirmed}
                    for e in d.queue
                ]
                self.store.update_charging(d.station_id, {
                    "station_id": d.station_id,
                    "dock_x": d.dock_x,
                    "dock_y": d.dock_y,
                    "dock_robot": d.docked_robot_id,
                    "queue": queue,
                })

    def _poll_coverage(self):
        for sample in self._cov_reader.take():
            if sample.info.valid:
                d = sample.data
                self.store.update_coverage(d.robot_id, d.x, d.y)

    # ── command sending ────────────────────────────────────────────────────

    def send_command(self, robot_id: str, command: str, *,
                     goto_x: float = 0, goto_y: float = 0,
                     goto_speed: float = 0,
                     waypoints: Optional[List[dict]] = None) -> dict:
        """Send a command to a robot via rti.rpc.Requester."""
        cmd_map = {
            "STOP":        Command.CMD_STOP,
            "FOLLOW_PATH": Command.CMD_FOLLOW_PATH,
            "GOTO":        Command.CMD_GOTO,
            "RESUME":      Command.CMD_RESUME,
            "SET_PATH":    Command.CMD_SET_PATH,
            "CHARGE":      Command.CMD_CHARGE,
        }
        cmd_enum = cmd_map.get(command)
        if cmd_enum is None:
            return {"success": False, "description": f"Unknown command: {command}"}

        # Build typed parameters (no JSON encoding)
        goto_params = None
        set_path_params = None
        if cmd_enum == Command.CMD_GOTO:
            goto_params = GotoParameters(x=goto_x, y=goto_y, speed=goto_speed)
        elif cmd_enum == Command.CMD_SET_PATH and waypoints:
            set_path_params = SetPathParameters(
                waypoints=[Waypoint(x=w["x"], y=w["y"]) for w in waypoints])
        elif cmd_enum in (Command.CMD_FOLLOW_PATH, Command.CMD_RESUME) and goto_speed > 0:
            goto_params = GotoParameters(speed=goto_speed)

        req = CommandRequest(
            robot_id=robot_id,
            command=cmd_enum,
            goto_params=goto_params,
            set_path_params=set_path_params,
        )

        try:
            request_id = self.command_requester.send_request(req)
            replies = self.command_requester.receive_replies(
                dds.Duration.from_seconds(5),
                related_request_id=request_id,
            )
            # Find the reply from the target robot (fan-out means all robots
            # respond, but only the target robot's reply is meaningful)
            for reply in replies:
                if reply.info.valid and reply.data.robot_id == robot_id:
                    r = reply.data
                    return {
                        "success": r.success,
                        "description": r.description,
                        "resulting_status": r.resulting_status.name,
                        "resulting_intent": r.resulting_intent.name,
                    }
            return {"success": False, "description": "No matching robot responded"}
        except dds.TimeoutError:
            return {"success": False, "description": f"Timeout waiting for {robot_id}"}
        except Exception as e:
            return {"success": False, "description": str(e)}

    def send_command_all(self, command: str, *,
                         goto_x: float = 0, goto_y: float = 0,
                         goto_speed: float = 0,
                         waypoints: Optional[List[dict]] = None) -> dict:
        """Send a command to every known robot, one at a time."""
        robot_ids = self.store.known_robots()
        results: dict = {}
        for rid in robot_ids:
            results[rid] = self.send_command(rid, command,
                                             goto_x=goto_x, goto_y=goto_y,
                                             goto_speed=goto_speed,
                                             waypoints=waypoints)
        n = len(robot_ids)
        successes = sum(1 for r in results.values() if r.get("success"))
        return {
            "broadcast": True,
            "command": command,
            "calls_made": n,
            "success": successes == n,
            "description": f"{successes}/{n} robots acknowledged {command}",
            "results": results,
        }

    def get_video_frame(self, robot_id: str) -> Optional[bytes]:
        with self._video_lock:
            return self._video_frames.get(robot_id)

    # ── Video robot selection (partition-based matching) ──────────

    _VIDEO_SENTINEL = "__NONE__"

    def select_video_robot(self, robot_id: str):
        """Switch the onboard camera to a different robot.

        A single DDS knob is turned — the video Subscriber's partition:

        **Partition QoS** on ``self._video_subscriber`` → ``[robot_id]``

        Each robot's VideoFrame DataWriter sits on a Publisher whose
        partition is the robot's own ID.  Changing the Subscriber
        partition to a robot_id makes DDS match that specific
        writer/reader pair, which:
          • triggers ``publication_matched_status`` on the matched
            robot's writer (current_count goes from 0 → 1) — the robot
            starts rendering and publishing JPEG frames.
          • unmatches the previous robot (current_count goes from
            1 → 0) — it stops rendering immediately.

        No content filter, no property inspection, no polling.
        """
        if robot_id == self._active_video_robot:
            return  # already viewing this robot

        # Clear stale frames from the previous robot
        with self._video_lock:
            self._video_frames.clear()

        # Bump generation — kills orphan MJPEG generators
        self._video_generation += 1

        # Change the video Subscriber's partition to the selected robot
        qos = self._video_subscriber.qos
        qos.partition.name = [robot_id]
        self._video_subscriber.qos = qos

        self._active_video_robot = robot_id
        print(f"[ui] 📷 Video switched to {robot_id} (gen={self._video_generation})")

    def deselect_video(self):
        """Stop the video stream — set Subscriber partition back to sentinel.

        All robot writers see ``publication_matched_status.current_count == 0``
        → none of them render.  The Subscriber partition ``'__NONE__'``
        doesn't match any Publisher partition → no data flows.
        """
        # Subscriber partition → sentinel (matches nothing)
        qos = self._video_subscriber.qos
        qos.partition.name = [self._VIDEO_SENTINEL]
        self._video_subscriber.qos = qos

        self._active_video_robot = None
        self._video_generation += 1  # kill orphan MJPEG generators
        with self._video_lock:
            self._video_frames.clear()
        print(f"[ui] 📷 Video stopped — all robots idle (gen={self._video_generation})")


# ─────────────────────────────────────────────────────────────────────────────
# Presentation layer – Flask web UI
# ─────────────────────────────────────────────────────────────────────────────
DASHBOARD_HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Robot Fleet Dashboard — Pure DDS</title>
<style>
  :root {
    --bg: #1e1e2e; --panel: #2a2a3d; --header: #3b3b55;
    --text: #cdd6f4; --dim: #6c7086; --blue: #89b4fa;
    --green: #a6e3a1; --yellow: #f9e2af; --red: #f38ba8;
    --peach: #fab387; --canvas: #181825; --grid: #313244; --border: #45475a;
  }
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family: "Menlo","Consolas",monospace; font-size:13px;
         background:var(--bg); color:var(--text); }
  header { background:var(--header); padding:12px 20px; font-size:15px;
           font-weight:bold; color:var(--blue); }
  .wrap { display:flex; gap:8px; padding:8px; height:calc(100vh - 50px); }

  /* --- map --- */
  .map-panel { flex:1; background:var(--panel); border-radius:6px; padding:8px;
               display:flex; flex-direction:column; }
  .map-panel h3 { color:var(--blue); margin-bottom:6px; font-size:12px; }
  canvas { flex:1; border-radius:4px; }

  /* --- right panel --- */
  .data-panel { width:480px; display:flex; flex-direction:column; gap:8px;
                overflow-y:auto; }
  .section { background:var(--panel); border-radius:6px; padding:10px 14px; }
  .section h3 { color:var(--blue); font-size:12px; margin-bottom:6px; }
  table { width:100%; border-collapse:collapse; }
  td { padding:2px 6px; white-space:nowrap; }
  .rid { color:var(--blue); font-weight:bold; }
  .ok  { color:var(--green); } .warn { color:var(--yellow); } .crit { color:var(--red); }
  .conn-dot { font-weight:bold; }

  /* --- collapsible sections --- */
  .section h3, .cmd-panel h3, .video-panel h3 {
    cursor:pointer; user-select:none; transition:color 0.15s;
  }
  .section h3:hover, .cmd-panel h3:hover, .video-panel h3:hover { color:var(--text); }
  .section h3::before, .cmd-panel h3::before, .video-panel h3::before {
    content:""; display:inline-block; width:0; height:0;
    border-left:5px solid transparent; border-right:5px solid transparent;
    border-top:6px solid var(--blue); margin-right:6px;
    transition:transform 0.2s; vertical-align:middle;
  }
  .collapsed h3::before { transform:rotate(-90deg); }
  .collapsed .panel-body { display:none; }

  /* --- command panel --- */
  .cmd-panel { background:var(--panel); border-radius:6px; padding:10px 14px; }
  .cmd-panel h3 { color:var(--blue); font-size:12px; margin-bottom:8px; }
  .cmd-row { display:flex; gap:6px; align-items:center; margin-bottom:6px; flex-wrap:wrap; }
  .cmd-row label { color:var(--dim); font-size:11px; min-width:28px; }
  .cmd-row select, .cmd-row input {
    background:var(--bg); color:var(--text); border:1px solid var(--border);
    border-radius:4px; padding:4px 8px; font-family:inherit; font-size:12px;
  }
  .cmd-row input { width:60px; }
  .cmd-row input.wide { width:80px; }
  .cmd-btns { display:flex; gap:6px; margin-top:8px; }
  .cmd-btns button {
    background:var(--header); color:var(--text); border:1px solid var(--border);
    border-radius:4px; padding:5px 12px; font-family:inherit; font-size:12px;
    cursor:pointer; transition: background 0.15s;
  }
  .cmd-btns button:hover { background:var(--blue); color:var(--bg); }
  .cmd-btns button.goto-btn { border-color:var(--blue); color:var(--blue); }
  .cmd-btns button.goto-btn:hover { background:var(--blue); color:var(--bg); }
  .cmd-btns button.stop-btn { border-color:var(--red); color:var(--red); }
  .cmd-btns button.stop-btn:hover { background:var(--red); color:var(--bg); }
  .cmd-btns button.path-btn { border-color:var(--green); color:var(--green); }
  .cmd-btns button.path-btn:hover { background:var(--green); color:var(--bg); }
  .cmd-btns button.resume-btn { border-color:var(--yellow); color:var(--yellow); }
  .cmd-btns button.resume-btn:hover { background:var(--yellow); color:var(--bg); }
  .cmd-btns button.charge-btn { border-color:#fab387; color:#fab387; }
  .cmd-btns button.charge-btn:hover { background:#fab387; color:var(--bg); }
  .cmd-result { color:var(--dim); font-size:11px; margin-top:6px; min-height:14px; }
  .cmd-hint { color:var(--text); font-size:10px; margin-top:6px; font-style:normal;
              line-height:1.6; opacity:0.85; }
  .cmd-hint kbd { background:var(--header); color:var(--blue); border:1px solid var(--border);
                  border-radius:3px; padding:1px 5px; font-family:inherit; font-size:10px; }

  /* --- video panel --- */
  .video-panel { background:var(--panel); border-radius:6px; padding:10px 14px; }
  .video-panel h3 { color:var(--blue); font-size:12px; margin-bottom:8px; }
  .video-row { display:flex; gap:6px; align-items:center; margin-bottom:6px; }
  .video-row select { background:var(--bg); color:var(--text); border:1px solid var(--border);
                      border-radius:4px; padding:4px 8px; font-family:inherit; font-size:12px; }
  .video-btns { display:flex; gap:6px; margin-bottom:8px; }
  .video-btns button { background:var(--header); color:var(--text); border:1px solid var(--border);
                       border-radius:4px; padding:5px 12px; font-family:inherit; font-size:12px;
                       cursor:pointer; transition:background 0.15s; }
  .video-btns button:hover { background:var(--blue); color:var(--bg); }
  .video-btns button.vid-stop { border-color:var(--red); color:var(--red); }
  .video-btns button.vid-stop:hover { background:var(--red); color:var(--bg); }
  .video-container { background:var(--canvas); border-radius:4px; overflow:hidden;
                     min-height:60px; display:flex; align-items:center; justify-content:center; }
  .video-container img { width:100%; display:block; }
  .video-container .placeholder { color:var(--dim); font-size:11px; padding:20px; text-align:center; }
</style>
</head>
<body>
<header>🤖 Robot Fleet Dashboard — the DDS approach: Pure DDS (Connext) <span id="hdr-stats" style="font-size:12px;font-weight:normal;color:var(--dim);margin-left:16px;"></span></header>
<div class="wrap">
  <div class="map-panel">
    <h3>Position Map (0–100 × 0–100)</h3>
    <canvas id="map"></canvas>
  </div>
  <div class="data-panel">
    <div class="cmd-panel">
      <h3>Commands</h3>
      <div class="panel-body">
      <div class="cmd-row">
        <label>Robot</label>
        <select id="cmd-robot"></select>
      </div>
      <div class="cmd-row">
        <label>X</label><input id="cmd-x" type="number" min="0" max="100" step="1" value="50">
        <label>Y</label><input id="cmd-y" type="number" min="0" max="100" step="1" value="50">
        <label>Speed</label><input id="cmd-speed" type="number" min="0.5" max="20" step="0.5" value="2.0" class="wide">
      </div>
      <div class="cmd-btns">
        <button class="goto-btn" onclick="sendGoto()">GOTO</button>
        <button class="path-btn" onclick="sendSimple('FOLLOW_PATH')">PATH</button>
        <button class="stop-btn" onclick="sendSimple('STOP')">STOP</button>
        <button class="resume-btn" onclick="sendSimple('RESUME')">RESUME</button>
        <button class="charge-btn" onclick="sendSimple('CHARGE')">⚡ CHARGE</button>
      </div>
      <div class="cmd-result" id="cmd-result"></div>
      <div class="cmd-hint">
        <kbd>Click</kbd> map → set GOTO target &nbsp;·&nbsp;
        <kbd>Drag</kbd> waypoint → move &nbsp;·&nbsp;
        <kbd>Double-click</kbd> → add waypoint &nbsp;·&nbsp;
        <kbd>⌥+Click</kbd> waypoint → remove &nbsp;·&nbsp;
        <button id="toggle-cov-btn" onclick="toggleCoverage()" style="font-size:11px;padding:3px 10px;border:1px solid #6c7086;background:#313244;color:#cdd6f4;border-radius:4px;cursor:pointer;">Coverage ✓</button>
        <button onclick="clearTrails()" style="font-size:11px;padding:3px 10px;border:1px solid #6c7086;background:transparent;color:#cdd6f4;border-radius:4px;cursor:pointer;">Clear Coverage</button>
      </div>
      </div>
    </div>
    <div class="video-panel">
      <h3>Onboard Camera</h3>
      <div class="panel-body">
      <div class="video-row">
        <label style="color:var(--dim);font-size:11px;min-width:28px;">Robot</label>
        <select id="vid-robot"></select>
      </div>
      <div class="video-btns">
        <button onclick="startVideo()">📹 Start</button>
        <button class="vid-stop" onclick="stopVideo()">⏹ Stop</button>
      </div>
      <div class="video-container" id="vid-container">
        <div class="placeholder">Select a robot and click Start</div>
      </div>
      </div>
    </div>
    <div class="section"><h3>Kinematic State <span style="color:var(--dim);font-weight:normal;font-size:10px">10 Hz</span></h3><div class="panel-body"><table id="t-kinematic"><tbody></tbody></table></div></div>
    <div class="section"><h3>Operational State <span style="color:var(--dim);font-weight:normal;font-size:10px">on-change</span></h3><div class="panel-body"><table id="t-operational"><tbody></tbody></table></div></div>
    <div class="section"><h3>Intent <span style="color:var(--dim);font-weight:normal;font-size:10px">on-change</span></h3><div class="panel-body"><table id="t-intent"><tbody></tbody></table></div></div>
    <div class="section"><h3>Telemetry <span style="color:var(--dim);font-weight:normal;font-size:10px">1 Hz</span></h3><div class="panel-body"><table id="t-telemetry"><tbody></tbody></table><div style="margin-top:6px;font-size:10px;color:var(--dim);font-style:italic">DDS: zero per-robot connections — middleware delivers via multicast from a single write() call</div></div></div>
    <div class="section"><h3>⚡ Charging Stations <span style="color:var(--dim);font-weight:normal;font-size:10px">stream</span></h3><div class="panel-body"><div id="charging-panel" style="font-size:12px;color:var(--dim);">Waiting for station data…</div></div></div>
    <div class="section"><h3>DDS Discovery</h3><div class="panel-body"><div id="dds-info" style="font-size:12px;color:var(--dim);">Waiting for data…</div></div></div>
  </div>
</div>

<script>
// --- Collapsible panels ---
document.querySelectorAll(".section h3, .cmd-panel h3, .video-panel h3").forEach(h3 => {
  h3.addEventListener("click", () => {
    h3.parentElement.classList.toggle("collapsed");
  });
});

const COLORS = ["#89b4fa","#a6e3a1","#fab387","#f9e2af","#f38ba8",
                "#cba6f7","#94e2d5","#f5c2e7","#74c7ec","#b4befe"];
let colorMap = {};
let colorIdx = 0;
function robotColor(rid) {
  if (!colorMap[rid]) colorMap[rid] = COLORS[colorIdx++ % COLORS.length];
  return colorMap[rid];
}
function cls(v, lo, hi) { return v > hi ? "crit" : v > lo ? "warn" : "ok"; }

// --- Coverage data from DDS CoveragePoint topic (server-provided) ---
let coverageData = {};  // rid → [{x, y, seq}, …] from SSE
let showCoverage = true;
function toggleCoverage() {
  showCoverage = !showCoverage;
  const btn = document.getElementById('toggle-cov-btn');
  btn.textContent = showCoverage ? 'Coverage ✓' : 'Coverage ✗';
  btn.style.background = showCoverage ? '#313244' : 'transparent';
}
function clearTrails() {
  fetch('/clear_coverage', {method: 'POST'});
  coverageData = {};
}

// --- Preload ground texture for canvas map ---
let groundImg = null;
{
  const img = new Image();
  img.onload = () => { groundImg = img; };
  img.src = "/ground_texture.jpg";
}

// --- SSE stream ---
const src = new EventSource("/stream");
src.onmessage = (e) => {
  const d = JSON.parse(e.data);
  refreshRobotDropdown(d.state);
  updateKinematic(d.kinematic);
  updateOperational(d.operational);
  updateIntent(d.intent);
  updateTelemetry(d.telemetry);
  updateDdsInfo(d);
  updateCharging(d.charging || {}, d.operational || {});
  // Update header stats badge
  const robotCount = Object.keys(d.state).length;
  const stationCount = Object.keys(d.charging || {}).length;
  const domainId = d.domain_id ?? 0;
  if (robotCount > 0 || stationCount > 0) {
    document.getElementById("hdr-stats").textContent =
      `${robotCount} robots · ${stationCount} stations · DDS domain ${domainId}`;
  }
  // Stash intent data for waypoint hit-testing (but don't overwrite during drag)
  if (!dragging) {
    lastIntentData = d.intent || {};
  }
  lastChargingData = d.charging || {};
  lastOperationalData = d.operational || {};
  // Update coverage data from server (DDS CoveragePoint topic)
  coverageData = d.coverage || {};
  drawMap(d.state, dragging ? lastIntentData : d.intent);
};

function updateKinematic(kin) {
  const tb = document.querySelector("#t-kinematic tbody");
  tb.innerHTML = "";
  for (const rid of Object.keys(kin).sort()) {
    const k = kin[rid];
    const spd = Math.sqrt((k.vx||0)**2 + (k.vy||0)**2);
    const hdg = ((k.heading||0) * 180 / Math.PI).toFixed(0);
    tb.innerHTML += `<tr>
      <td class="rid">${rid}</td>
      <td>(${(k.x??0).toFixed(1)}, ${(k.y??0).toFixed(1)})</td>
      <td>${spd.toFixed(1)} u/s</td>
      <td>${hdg}°</td></tr>`;
  }
}
function updateOperational(ops) {
  const tb = document.querySelector("#t-operational tbody");
  tb.innerHTML = "";
  for (const rid of Object.keys(ops).sort()) {
    const o = ops[rid];
    const batt = o.battery ?? 0;
    const bc = batt > 50 ? "ok" : batt > 20 ? "warn" : "crit";
    const st = o.status ?? "…";
    const isCharging = st === "STATUS_CHARGING";
    const stStyle = isCharging ? ' style="color:#fab387;font-weight:bold"' : '';
    const stLabel = isCharging ? "⚡ CHARGING" : st;
    tb.innerHTML += `<tr>
      <td class="rid">${rid}</td>
      <td${stStyle}>${stLabel}</td>
      <td class="${bc}">${batt.toFixed(1)}%</td></tr>`;
  }
}
function updateIntent(intent) {
  const tb = document.querySelector("#t-intent tbody");
  tb.innerHTML = "";
  for (const rid of Object.keys(intent).sort()) {
    const i = intent[rid];
    tb.innerHTML += `<tr>
      <td class="rid">${rid}</td>
      <td>${i.type}</td>
      <td>(${i.target_x.toFixed(1)}, ${i.target_y.toFixed(1)})</td></tr>`;
  }
}
function updateTelemetry(tel) {
  const tb = document.querySelector("#t-telemetry tbody");
  tb.innerHTML = "";
  for (const rid of Object.keys(tel).sort()) {
    const t = tel[rid];
    const sig = t.signal_strength ?? 100;
    tb.innerHTML += `<tr>
      <td class="rid">${rid}</td>
      <td class="${cls(t.cpu,50,75)}">CPU ${t.cpu.toFixed(1)}%</td>
      <td>MEM ${t.memory.toFixed(1)}%</td>
      <td class="${cls(t.temperature,55,65)}">${t.temperature.toFixed(1)}°C</td>
      <td class="${cls(100-sig,50,80)}">LNK ${sig.toFixed(0)}%</td></tr>`;
  }
}
function updateDdsInfo(d) {
  const panel = document.getElementById("dds-info");
  const robotCount = Object.keys(d.state).length;
  const stationCount = Object.keys(d.charging || {}).length;
  const domainId = d.domain_id ?? 0;
  panel.innerHTML = `<table style="width:100%;font-size:12px;">
    <tr><td style="color:var(--dim)">Domain ID</td><td style="color:var(--blue);font-weight:bold">${domainId}</td></tr>
    <tr><td style="color:var(--dim)">Robots discovered</td><td class="ok">${robotCount}</td></tr>
    <tr><td style="color:var(--dim)">Stations discovered</td><td style="color:var(--peach)">${stationCount}</td></tr>
    <tr><td style="color:var(--dim)">Transport</td><td style="color:var(--dim)">DDS SPDP / multicast</td></tr>
  </table>`;
}
function updateCharging(charging, operational) {
  const panel = document.getElementById("charging-panel");
  const ids = Object.keys(charging).sort();
  if (ids.length === 0) { panel.innerHTML = '<span style="color:var(--dim)">No stations discovered</span>'; return; }
  let html = '';
  for (const sid of ids) {
    const st = charging[sid];
    html += `<div style="margin-bottom:8px;">`;
    html += `<div style="font-weight:bold;color:#fab387;margin-bottom:4px;">⚡ ${sid} <span style="font-weight:normal;color:var(--dim);font-size:10px">(${st.dock_x}, ${st.dock_y})</span></div>`;
    if (st.queue && st.queue.length > 0) {
      html += `<table style="width:100%;font-size:11px;">`;
      html += `<tr style="color:var(--dim)"><td style="width:30px">#</td><td>Robot</td><td style="width:70px">Status</td></tr>`;
      for (const e of st.queue) {
        const isOnDock = (e.robot_id === st.dock_robot);
        const robotOps = operational[e.robot_id];
        const actuallyCharging = robotOps && robotOps.status === "STATUS_CHARGING";
        let statusTxt, statusCol;
        if (isOnDock && actuallyCharging) {
          statusTxt = '🔌 Charging';
          statusCol = '#a6e3a1';
        } else if (isOnDock) {
          statusTxt = '🚜 En route';
          statusCol = '#89b4fa';
        } else if (e.confirmed) {
          statusTxt = '⏳ Waiting';
          statusCol = '#f9e2af';
        } else {
          statusTxt = '… Pending';
          statusCol = 'var(--dim)';
        }
        const rowBg = (isOnDock && actuallyCharging) ? 'background:rgba(166,227,161,0.1);' : '';
        html += `<tr style="${rowBg}"><td style="color:var(--dim)">${e.rank}</td>`;
        html += `<td class="rid" style="${(isOnDock && actuallyCharging) ? 'font-weight:bold' : ''}">${e.robot_id}</td>`;
        html += `<td style="color:${statusCol}">${statusTxt}</td></tr>`;
      }
      html += `</table>`;
    } else {
      html += `<div style="color:var(--dim);font-size:11px">Idle</div>`;
    }
    html += `</div>`;
  }
  panel.innerHTML = html;
}

// --- Robot icon renderer (tractor) ---
function drawTractor(ctx, sx, sy, col, statusStr, label, heading) {
  const S = 0.44;
  const antCol = statusStr === "STATUS_HOLDING"  ? "#89b4fa"
               : statusStr === "STATUS_IDLE"     ? "#f38ba8"
               : statusStr === "STATUS_CHARGING" ? "#f9e2af"
               : "#22dd22";

  ctx.save();
  ctx.translate(sx, sy);
  ctx.rotate(heading + Math.PI/2);

  const ox = 0, oy = 0;

  // shadow
  ctx.fillStyle = "rgba(0,0,0,0.25)";
  ctx.beginPath();
  ctx.ellipse(2, 26, 26, 5, 0, 0, Math.PI*2);
  ctx.fill();

  const lw = 2.5;
  ctx.strokeStyle = col;
  ctx.lineWidth = lw;
  ctx.lineCap = "round";
  ctx.lineJoin = "round";

  // Cabin windows
  const cabY = -28, cabH = 18, cabGap = 2;
  const lwW = 12, rwW = 14;
  const cabTotalW = lwW + cabGap + rwW;
  const cabX = -cabTotalW/2;

  ctx.fillStyle = col; ctx.globalAlpha = 0.35;
  ctx.fillRect(ox + cabX, oy + cabY, lwW, cabH);
  ctx.globalAlpha = 1.0;
  ctx.strokeStyle = col; ctx.lineWidth = lw;
  ctx.strokeRect(ox + cabX, oy + cabY, lwW, cabH);

  ctx.fillStyle = col; ctx.globalAlpha = 0.35;
  ctx.fillRect(ox + cabX + lwW + cabGap, oy + cabY, rwW, cabH);
  ctx.globalAlpha = 1.0;
  ctx.strokeStyle = col; ctx.lineWidth = lw;
  ctx.strokeRect(ox + cabX + lwW + cabGap, oy + cabY, rwW, cabH);

  // Cabin roof
  ctx.fillStyle = col; ctx.globalAlpha = 0.5;
  ctx.fillRect(ox + cabX - 2, oy + cabY - 3, cabTotalW + 4, 3);
  ctx.globalAlpha = 1.0;
  ctx.strokeStyle = col; ctx.lineWidth = lw + 0.5;
  ctx.beginPath();
  ctx.moveTo(ox + cabX - 2, oy + cabY);
  ctx.lineTo(ox + cabX + cabTotalW + 2, oy + cabY);
  ctx.stroke();

  // Neck / pillar
  const neckX1 = cabX + lwW + cabGap/2 - 1;
  const neckX2 = neckX1 + 2;
  const neckTop = cabY + cabH;
  const neckBot = cabY + cabH + 8;
  ctx.strokeStyle = col; ctx.lineWidth = lw;
  ctx.beginPath();
  ctx.moveTo(ox + neckX1, oy + neckTop); ctx.lineTo(ox + neckX1, oy + neckBot);
  ctx.moveTo(ox + neckX2, oy + neckTop); ctx.lineTo(ox + neckX2, oy + neckBot);
  ctx.stroke();

  // Chassis bar
  const chY = neckBot;
  const chHalfW = 22;

  // Body plate
  const plateTop = neckTop;
  const plateBot = chY + 18;
  const plateHalfW = 10;
  ctx.fillStyle = col; ctx.globalAlpha = 0.25;
  ctx.fillRect(ox - plateHalfW, oy + plateTop, plateHalfW * 2, plateBot - plateTop);
  ctx.globalAlpha = 1.0;

  ctx.strokeStyle = col; ctx.lineWidth = lw + 0.5;
  ctx.beginPath();
  ctx.moveTo(ox - chHalfW, oy + chY);
  ctx.lineTo(ox + chHalfW, oy + chY);
  ctx.stroke();

  // Wheels
  const wW = 10, wH = 24;
  const wY = chY - 2;
  const wLeftX = -chHalfW;
  const wRightX = chHalfW - wW;
  const wr = 3;

  ctx.beginPath(); ctx.roundRect(ox + wLeftX, oy + wY, wW, wH, wr);
  ctx.fillStyle = col; ctx.globalAlpha = 0.7; ctx.fill();
  ctx.globalAlpha = 1.0; ctx.strokeStyle = col; ctx.lineWidth = lw; ctx.stroke();

  ctx.beginPath(); ctx.roundRect(ox + wRightX, oy + wY, wW, wH, wr);
  ctx.fillStyle = col; ctx.globalAlpha = 0.7; ctx.fill();
  ctx.globalAlpha = 1.0; ctx.strokeStyle = col; ctx.lineWidth = lw; ctx.stroke();

  // Wheel hub lines
  ctx.strokeStyle = "#1e1e2e"; ctx.lineWidth = 1; ctx.globalAlpha = 0.5;
  for (const dx of [wLeftX, wRightX]) {
    for (let i = 1; i <= 3; i++) {
      const ly = wY + i * (wH / 4);
      ctx.beginPath();
      ctx.moveTo(ox + dx + 2, oy + ly); ctx.lineTo(ox + dx + wW - 2, oy + ly);
      ctx.stroke();
    }
  }
  ctx.globalAlpha = 1.0;

  // Axle bar
  const axleY = wY + wH - 3;
  ctx.strokeStyle = col; ctx.lineWidth = lw;
  ctx.beginPath();
  ctx.moveTo(ox + wLeftX + wW, oy + axleY);
  ctx.lineTo(ox + wRightX, oy + axleY);
  ctx.stroke();

  // Status beacon
  const beaconR = 6;
  const beaconX = ox;
  const beaconY = cabY + cabH / 2;
  ctx.save();
  ctx.shadowColor = antCol; ctx.shadowBlur = 12;
  ctx.beginPath(); ctx.arc(beaconX, oy + beaconY, beaconR, 0, Math.PI*2);
  ctx.fillStyle = antCol; ctx.fill();
  ctx.restore();
  ctx.strokeStyle = col; ctx.lineWidth = 1.5;
  ctx.beginPath(); ctx.arc(beaconX, oy + beaconY, beaconR, 0, Math.PI*2); ctx.stroke();

  // Label (outside rotation so text stays upright)
  ctx.restore();
  ctx.fillStyle = col; ctx.font = "bold 12px Menlo"; ctx.textAlign = "center";
  ctx.fillText(label, sx, sy + wY + wH + 16);
  ctx.lineCap = "butt";
}

// --- Canvas map ---
function drawMap(state, intent) {
  const cv = document.getElementById("map");
  const ctx = cv.getContext("2d");
  cv.width = cv.clientWidth;
  cv.height = cv.clientHeight;
  const W = cv.width, H = cv.height, M = 30;

  ctx.fillStyle = "#181825"; ctx.fillRect(0,0,W,H);

  // Ground texture
  if (groundImg) {
    ctx.drawImage(groundImg, M, M, W - 2*M, H - 2*M);
    ctx.fillStyle = "rgba(24,24,37,0.35)"; ctx.fillRect(M,M,W-2*M,H-2*M);
  }

  // Grid
  ctx.font = "10px Menlo"; ctx.textAlign = "center";
  const gridCol = groundImg ? "rgba(255,255,255,0.12)" : "#313244";
  const borderCol = groundImg ? "rgba(255,255,255,0.30)" : "#45475a";
  for (let i = 0; i <= 100; i += 20) {
    const x = M + i/100*(W-2*M), y = M + (1-i/100)*(H-2*M);
    ctx.strokeStyle = gridCol; ctx.lineWidth = 1;
    ctx.beginPath(); ctx.moveTo(x,M); ctx.lineTo(x,H-M); ctx.stroke();
    ctx.beginPath(); ctx.moveTo(M,y); ctx.lineTo(W-M,y); ctx.stroke();
    ctx.fillStyle = "#6c7086";
    ctx.fillText(i, x, H-M+14);
    ctx.textAlign = "right"; ctx.fillText(i, M-6, y+4); ctx.textAlign = "center";
  }
  ctx.strokeStyle = borderCol; ctx.strokeRect(M,M,W-2*M,H-2*M);

  function toPx(px,py) { return [M+px/100*(W-2*M), M+(1-py/100)*(H-2*M)]; }

  // --- Charging station icons ---
  let stationsToDraw = [];
  const chargingIds = Object.keys(lastChargingData);
  if (chargingIds.length > 0) {
    for (const sid of chargingIds) {
      const s = lastChargingData[sid];
      stationsToDraw.push({x: s.dock_x, y: s.dock_y, id: sid, dock_robot: s.dock_robot, queue: s.queue || []});
    }
  }
  for (const st of stationsToDraw) {
    const [dx, dy] = toPx(st.x, st.y);
    const dockOps = st.dock_robot ? lastOperationalData[st.dock_robot] : null;
    const isCharging = dockOps && dockOps.status === "STATUS_CHARGING";
    const isEnRoute = !!st.dock_robot && !isCharging;
    ctx.save();
    ctx.shadowColor = "#fab387";
    ctx.shadowBlur = isCharging ? 20 : 10;
    ctx.fillStyle = isCharging ? "rgba(166,227,161,0.25)"
                  : isEnRoute  ? "rgba(137,180,250,0.20)"
                  :              "rgba(250,179,135,0.15)";
    ctx.beginPath(); ctx.arc(dx, dy, 18, 0, Math.PI*2); ctx.fill();
    ctx.restore();
    ctx.strokeStyle = isCharging ? "#a6e3a1" : isEnRoute ? "#89b4fa" : "#fab387";
    ctx.lineWidth = 2;
    ctx.beginPath(); ctx.arc(dx, dy, 14, 0, Math.PI*2); ctx.stroke();
    ctx.font = "bold 16px sans-serif";
    ctx.fillStyle = isCharging ? "#a6e3a1" : isEnRoute ? "#89b4fa" : "#fab387";
    ctx.textAlign = "center"; ctx.textBaseline = "middle";
    ctx.fillText("⚡", dx, dy);
    ctx.font = "9px Menlo";
    ctx.textBaseline = "top";
    const label = st.dock_robot ? st.dock_robot : "CHARGE";
    ctx.fillText(label, dx, dy + 18);
    const qLen = st.queue.length;
    if (qLen > 0) {
      ctx.font = "bold 9px Menlo"; ctx.fillStyle = "#f9e2af"; ctx.textBaseline = "top";
      ctx.fillText(`[${qLen}]`, dx, dy + 28);
    }
    ctx.textBaseline = "alphabetic";
  }

  // --- Coverage trail lines (from DDS CoveragePoint topic) ---
  // Points are distance-filtered at ≥1 arena unit at the source.
  // If consecutive points are >COV_GAP apart the robot was redirected
  // — start a new line segment instead of drawing a false connector.
  const COV_GAP = 5;
  if (showCoverage)
  for (const rid of Object.keys(coverageData)) {
    const trail = coverageData[rid];
    if (!trail || trail.length < 2) continue;
    const col = robotColor(rid);
    ctx.save();
    ctx.strokeStyle = col;
    ctx.globalAlpha = 0.45;
    ctx.lineWidth = 4;
    ctx.lineCap = "round"; ctx.lineJoin = "round";
    ctx.beginPath();
    const [fx, fy] = toPx(trail[0].x, trail[0].y);
    ctx.moveTo(fx, fy);
    for (let i = 1; i < trail.length; i++) {
      const [px, py] = toPx(trail[i].x, trail[i].y);
      const dx = trail[i].x - trail[i-1].x, dy = trail[i].y - trail[i-1].y;
      if (dx*dx + dy*dy > COV_GAP*COV_GAP) {
        ctx.stroke(); ctx.beginPath(); ctx.moveTo(px, py);
      } else {
        ctx.lineTo(px, py);
      }
    }
    ctx.stroke();
    ctx.restore();
  }

  // --- Per-robot rendering ---
  const allIds = [...new Set([...Object.keys(state),...Object.keys(intent)])].sort();
  for (const rid of allIds) {
    const col = robotColor(rid);
    if (!state[rid]) continue;
    const s = state[rid];
    const [sx,sy] = toPx(s.x, s.y);

    // Path route + intent arrow
    if (intent[rid]) {
      const idata = intent[rid];
      const [tx,ty] = toPx(idata.target_x, idata.target_y);

      if (idata.waypoints && idata.waypoints.length > 1) {
        const wps = idata.waypoints;
        ctx.setLineDash([4,6]); ctx.strokeStyle = col; ctx.lineWidth = 2.5;
        ctx.globalAlpha = 0.55;
        ctx.beginPath();
        const [fx,fy] = toPx(wps[0].x, wps[0].y);
        ctx.moveTo(fx,fy);
        for (let w=1; w<wps.length; w++) {
          const [wx,wy] = toPx(wps[w].x, wps[w].y);
          ctx.lineTo(wx,wy);
        }
        ctx.closePath(); ctx.stroke();
        ctx.globalAlpha = 1.0; ctx.setLineDash([]);

        for (let w=0; w<wps.length; w++) {
          const [wx,wy] = toPx(wps[w].x, wps[w].y);
          const isDragged = dragging && dragging.rid === rid && dragging.wpIndex === w;
          const r = isDragged ? 14 : 11;
          ctx.beginPath(); ctx.arc(wx,wy,r,0,Math.PI*2);
          ctx.fillStyle = isDragged ? "#fff" : col;
          ctx.globalAlpha = isDragged ? 0.9 : 0.7; ctx.fill();
          ctx.globalAlpha = 1.0;
          ctx.strokeStyle = isDragged ? "#f38ba8" : col;
          ctx.lineWidth = isDragged ? 3 : 2; ctx.stroke();
          ctx.fillStyle = isDragged ? "#1e1e2e" : "#fff";
          ctx.font = "bold 11px Menlo"; ctx.textAlign = "center";
          ctx.fillText(w, wx, wy+4);
        }
      }

      // Active intent arrow
      ctx.setLineDash([4,4]); ctx.strokeStyle = col; ctx.lineWidth = 1.5;
      ctx.beginPath(); ctx.moveTo(sx,sy); ctx.lineTo(tx,ty); ctx.stroke();
      ctx.setLineDash([]);
      const a = Math.atan2(ty-sy, tx-sx), al = 10;
      ctx.fillStyle = col; ctx.beginPath();
      ctx.moveTo(tx,ty);
      ctx.lineTo(tx-al*Math.cos(a-0.4), ty-al*Math.sin(a-0.4));
      ctx.lineTo(tx-al*Math.cos(a+0.4), ty-al*Math.sin(a+0.4));
      ctx.fill();
    }

    // Tractor icon with heading
    const statusStr = (state[rid] && state[rid].status) || "STATUS_MOVING";
    const vx = (state[rid] && state[rid].vx) || 0;
    const vy = (state[rid] && state[rid].vy) || 0;
    const heading = (Math.abs(vx) + Math.abs(vy) > 0.01)
      ? Math.atan2(-vy, vx)
      : -(s.heading || 0);
    drawTractor(ctx, sx, sy, col, statusStr, rid, heading);
  }

  // --- Pending GOTO crosshair ---
  if (gotoTarget) {
    const [gx, gy] = toPx(gotoTarget.x, gotoTarget.y);
    const r = 12;
    ctx.strokeStyle = "#ffffff"; ctx.lineWidth = 2;
    ctx.beginPath(); ctx.arc(gx, gy, r, 0, Math.PI*2); ctx.stroke();
    ctx.beginPath(); ctx.moveTo(gx-r-4, gy); ctx.lineTo(gx+r+4, gy); ctx.stroke();
    ctx.beginPath(); ctx.moveTo(gx, gy-r-4); ctx.lineTo(gx, gy+r+4); ctx.stroke();
    ctx.fillStyle = "#ffffff"; ctx.font = "10px Menlo"; ctx.textAlign = "center";
    ctx.fillText(`(${gotoTarget.x.toFixed(0)},${gotoTarget.y.toFixed(0)})`, gx, gy+r+14);
  }

  // --- Flash marker for waypoint add/remove ---
  if (flashMarker && Date.now() < flashMarker.until) {
    const [fx, fy] = toPx(flashMarker.x, flashMarker.y);
    const elapsed = Date.now() - (flashMarker.until - 600);
    const progress = elapsed / 600;
    const radius = 8 + progress * 14;
    ctx.globalAlpha = 1.0 - progress;
    ctx.strokeStyle = flashMarker.color; ctx.lineWidth = 3;
    ctx.beginPath(); ctx.arc(fx, fy, radius, 0, Math.PI*2); ctx.stroke();
    ctx.fillStyle = flashMarker.color;
    ctx.beginPath(); ctx.arc(fx, fy, 4, 0, Math.PI*2); ctx.fill();
    ctx.globalAlpha = 1.0;
  } else {
    flashMarker = null;
  }
}

// Resize canvas on window resize
window.addEventListener("resize", () => {
  const cv = document.getElementById("map");
  cv.width = cv.clientWidth; cv.height = cv.clientHeight;
});

// --- Command panel ---
let knownRobots = new Set();

function refreshRobotDropdown(state) {
  const ids = Object.keys(state).sort();
  const key = ids.join(",");

  const sel = document.getElementById("cmd-robot");
  if (sel.dataset.key !== key) {
    const prev = sel.value;
    sel.dataset.key = key;
    sel.innerHTML = "";
    for (const rid of ids) {
      const opt = document.createElement("option");
      opt.value = rid; opt.textContent = rid;
      sel.appendChild(opt);
    }
    const allOpt = document.createElement("option");
    allOpt.value = "*"; allOpt.textContent = "* ALL";
    sel.appendChild(allOpt);
    if (prev === "*" || ids.includes(prev)) sel.value = prev;
  }

  const vsel = document.getElementById("vid-robot");
  if (vsel.dataset.key !== key) {
    const vprev = vsel.value;
    vsel.dataset.key = key;
    vsel.innerHTML = "";
    for (const rid of ids) {
      const opt = document.createElement("option");
      opt.value = rid; opt.textContent = rid;
      vsel.appendChild(opt);
    }
    if (ids.includes(vprev)) vsel.value = vprev;
  }
}

// --- Video panel ---
let activeVideoRobot = null;

function startVideo() {
  const rid = document.getElementById("vid-robot").value;
  if (!rid) return;
  activeVideoRobot = rid;
  const container = document.getElementById("vid-container");
  container.innerHTML = `<img src="/video_feed/${rid}" alt="Onboard camera: ${rid}">`;
}

function stopVideo() {
  activeVideoRobot = null;
  const container = document.getElementById("vid-container");
  container.innerHTML = '<div class="placeholder">Select a robot and click Start</div>';
  // Tell the server to reset the video partition — robots stop rendering
  fetch("/video_stop", {method: "POST"}).catch(() => {});
}

async function sendCommand(robot_id, command, extra) {
  const el = document.getElementById("cmd-result");
  el.textContent = `Sending ${command}…`;
  el.style.color = "var(--dim)";
  try {
    const payload = Object.assign({robot_id, command}, extra || {});
    const resp = await fetch("/command", {
      method: "POST",
      headers: {"Content-Type": "application/json"},
      body: JSON.stringify(payload),
    });
    const data = await resp.json();

    if (data.broadcast) {
      const rows = Object.entries(data.results || {})
        .sort(([a],[b]) => a.localeCompare(b))
        .map(([rid, r]) => {
          const sym = r.success ? "✓" : "✗";
          const col = r.success ? "var(--green)" : "var(--red)";
          return `<span style="color:${col}">${sym} ${rid}</span>`;
        }).join("  ");
      el.innerHTML =
        `<span style="color:var(--yellow)">⬡ ${data.command} → all robots</span>  ` +
        `<span style="color:var(--peach)">(${data.calls_made} DDS requests)</span><br>` +
        rows;
    } else {
      const ok = data.success;
      let msg = `${ok ? "✓" : "✗"} ${data.description}`;
      if (ok && data.resulting_status) msg += ` [${data.resulting_status}/${data.resulting_intent}]`;
      el.textContent = msg;
      el.style.color = ok ? "var(--green)" : "var(--red)";
    }
  } catch (e) {
    el.textContent = `✗ ${e}`;
    el.style.color = "var(--red)";
  }
}

function sendGoto() {
  const rid = document.getElementById("cmd-robot").value;
  const x = parseFloat(document.getElementById("cmd-x").value);
  const y = parseFloat(document.getElementById("cmd-y").value);
  const spd = parseFloat(document.getElementById("cmd-speed").value) || 0;
  if (!rid) return;
  setTimeout(() => { gotoTarget = null; }, 1500);
  sendCommand(rid, "GOTO", {goto_x: x, goto_y: y, goto_speed: spd});
}

function sendSimple(cmd) {
  const rid = document.getElementById("cmd-robot").value;
  if (!rid) return;
  const spd = parseFloat(document.getElementById("cmd-speed").value) || 0;
  sendCommand(rid, cmd, {goto_speed: spd});
}

// --- Click on map: GOTO / drag waypoints / dblclick add / ⌥+click remove ---
let gotoTarget = null;
let dragging = null;
let lastIntentData = {};
let lastChargingData = {};
let lastOperationalData = {};
let dblClickPending = false;
let flashMarker = null;

function mouseToArena(e, cv) {
  const rect = cv.getBoundingClientRect();
  const mx = e.clientX - rect.left;
  const my = e.clientY - rect.top;
  const W = cv.width, H = cv.height, M = 30;
  const ax = (mx - M) / (W - 2*M) * 100;
  const ay = (1 - (my - M) / (H - 2*M)) * 100;
  return {ax, ay, inBounds: ax >= 0 && ax <= 100 && ay >= 0 && ay <= 100};
}

function hitTestWaypoint(ax, ay) {
  const hitRadius = 6;
  for (const rid of Object.keys(lastIntentData)) {
    const idata = lastIntentData[rid];
    if (!idata || !idata.waypoints) continue;
    for (let i = 0; i < idata.waypoints.length; i++) {
      const wp = idata.waypoints[i];
      const dx = wp.x - ax, dy = wp.y - ay;
      if (Math.sqrt(dx*dx + dy*dy) < hitRadius) {
        return {rid, wpIndex: i, waypoints: idata.waypoints.map(w => ({x:w.x, y:w.y}))};
      }
    }
  }
  return null;
}

function findNearestRoute(ax, ay) {
  let best = null, bestDist = Infinity;
  for (const rid of Object.keys(lastIntentData)) {
    const idata = lastIntentData[rid];
    if (!idata || !idata.waypoints || idata.waypoints.length < 2) continue;
    const wps = idata.waypoints;
    for (let i = 0; i < wps.length; i++) {
      const a = wps[i], b = wps[(i+1) % wps.length];
      const mx = (a.x + b.x) / 2, my = (a.y + b.y) / 2;
      const d = Math.sqrt((ax-mx)*(ax-mx) + (ay-my)*(ay-my));
      const da = Math.sqrt((ax-a.x)*(ax-a.x) + (ay-a.y)*(ay-a.y));
      const segDist = Math.min(d, da);
      if (segDist < bestDist) {
        bestDist = segDist;
        best = {rid, insertIndex: (i+1) % wps.length, waypoints: wps.map(w => ({x:w.x, y:w.y}))};
      }
    }
  }
  return best;
}

const mapCanvas = document.getElementById("map");

mapCanvas.addEventListener("mousedown", (e) => {
  const {ax, ay, inBounds} = mouseToArena(e, mapCanvas);
  if (!inBounds) return;

  const hit = hitTestWaypoint(ax, ay);
  if (hit) {
    if (e.altKey) {
      const el = document.getElementById("cmd-result");
      if (hit.waypoints.length <= 2) {
        el.textContent = "✗ Path needs at least 2 waypoints";
        el.style.color = "var(--red)";
        return;
      }
      hit.waypoints.splice(hit.wpIndex, 1);
      const removedWp = lastIntentData[hit.rid].waypoints[hit.wpIndex];
      flashMarker = {x: removedWp.x, y: removedWp.y, color: "#f38ba8", until: Date.now() + 600};
      lastIntentData[hit.rid].waypoints = hit.waypoints;
      el.textContent = `Removing waypoint from ${hit.rid}'s path…`;
      el.style.color = "var(--peach)";
      sendCommand(hit.rid, "SET_PATH", {waypoints: hit.waypoints});
      e.preventDefault();
      return;
    }
    dragging = hit;
    mapCanvas.style.cursor = "grabbing";
    e.preventDefault();
  }
});

mapCanvas.addEventListener("mousemove", (e) => {
  const {ax, ay, inBounds} = mouseToArena(e, mapCanvas);
  if (dragging) {
    if (inBounds) {
      dragging.waypoints[dragging.wpIndex] = {x: ax, y: ay};
      if (lastIntentData[dragging.rid]) {
        lastIntentData[dragging.rid].waypoints = dragging.waypoints;
      }
    }
    e.preventDefault();
    return;
  }
  if (inBounds) {
    const hit = hitTestWaypoint(ax, ay);
    mapCanvas.style.cursor = hit ? (e.altKey ? "not-allowed" : "grab") : "crosshair";
  }
});

mapCanvas.addEventListener("mouseup", (e) => {
  if (dragging) {
    const {rid, waypoints} = dragging;
    dragging = null;
    mapCanvas.style.cursor = "crosshair";
    sendCommand(rid, "SET_PATH", {waypoints});
    return;
  }
  if (e.altKey) return;
  if (dblClickPending) return;
  const {ax, ay, inBounds} = mouseToArena(e, mapCanvas);
  if (!inBounds) return;
  if (hitTestWaypoint(ax, ay)) return;
  dblClickPending = true;
  setTimeout(() => {
    if (dblClickPending) {
      document.getElementById("cmd-x").value = ax.toFixed(1);
      document.getElementById("cmd-y").value = ay.toFixed(1);
      gotoTarget = {x: ax, y: ay};
    }
    dblClickPending = false;
  }, 250);
});

mapCanvas.addEventListener("dblclick", (e) => {
  dblClickPending = false;
  gotoTarget = null;
  const {ax, ay, inBounds} = mouseToArena(e, mapCanvas);
  if (!inBounds) return;
  if (hitTestWaypoint(ax, ay)) return;
  const nearest = findNearestRoute(ax, ay);
  if (!nearest) {
    const el = document.getElementById("cmd-result");
    el.textContent = "✗ No path route to add waypoint to";
    el.style.color = "var(--red)";
    return;
  }
  nearest.waypoints.splice(nearest.insertIndex, 0, {x: ax, y: ay});
  flashMarker = {x: ax, y: ay, color: "#a6e3a1", until: Date.now() + 600};
  if (lastIntentData[nearest.rid]) {
    lastIntentData[nearest.rid].waypoints = nearest.waypoints;
  }
  const el = document.getElementById("cmd-result");
  el.textContent = `Adding waypoint to ${nearest.rid}'s path…`;
  el.style.color = "var(--green)";
  sendCommand(nearest.rid, "SET_PATH", {waypoints: nearest.waypoints});
  e.preventDefault();
});

mapCanvas.addEventListener("mouseleave", () => {
  if (dragging) {
    dragging = null;
    mapCanvas.style.cursor = "crosshair";
  }
});
</script>
</body>
</html>"""


def create_app(store: FleetStateStore, client: DdsFleetClient) -> Flask:
    """Create the Flask app.

    *store* is the read-only data source for SSE snapshots.
    *client* is used for sending commands and video frames.
    """
    app = Flask(__name__)

    @app.route("/")
    def index():
        return render_template_string(DASHBOARD_HTML)

    @app.route("/stream")
    def stream():
        def generate():
            while client.running:
                data = json.dumps(store.snapshot())
                yield f"data: {data}\n\n"
                time.sleep(0.2)  # 5 Hz
        return Response(generate(), mimetype="text/event-stream",
                        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"})

    @app.route("/command", methods=["POST"])
    def command():
        body = request.get_json(force=True)
        robot_id = body.get("robot_id", "")
        cmd = body.get("command", "")
        goto_x = float(body.get("goto_x", 0))
        goto_y = float(body.get("goto_y", 0))
        goto_speed = float(body.get("goto_speed", 0))
        waypoints = body.get("waypoints", None)
        if robot_id == "*":
            result = client.send_command_all(cmd,
                                             goto_x=goto_x, goto_y=goto_y,
                                             goto_speed=goto_speed,
                                             waypoints=waypoints)
        else:
            result = client.send_command(robot_id, cmd,
                                         goto_x=goto_x, goto_y=goto_y,
                                         goto_speed=goto_speed,
                                         waypoints=waypoints)
        return jsonify(result)

    @app.route("/video_feed/<robot_id>")
    def video_feed(robot_id):
        """MJPEG stream from a robot's onboard camera via DDS VideoFrame topic.

        On first call (or when the robot changes), switches the video
        Subscriber's partition to the selected robot_id.  Only the
        matched robot's DataWriter publishes frames — all others see
        publication_matched_status.current_count == 0 and skip rendering.

        The browser renders this with a simple ``<img src="…">``.
        Each JPEG frame is delivered as a MIME multipart chunk.
        """
        # Tell DDS to match this robot's partition
        client.select_video_robot(robot_id)
        my_gen = client._video_generation

        def generate():
            _yield_count = 0
            _miss_count = 0
            while client.running:
                # Exit if user switched to another robot
                if client._video_generation != my_gen:
                    print(f"[ui] 📷 MJPEG {robot_id}: generation changed "
                          f"({my_gen} → {client._video_generation}) — exiting")
                    break
                frame = client.get_video_frame(robot_id)
                if frame:
                    _yield_count += 1
                    _miss_count = 0
                    if _yield_count % 25 == 0:
                        print(f"[ui] 📷 MJPEG {robot_id}: "
                              f"{_yield_count} yields")
                    yield (b"--frame\r\n"
                           b"Content-Type: image/jpeg\r\n\r\n"
                           + frame + b"\r\n")
                else:
                    _miss_count += 1
                    if _miss_count == 50:
                        active = client._active_video_robot
                        print(f"[ui] 📷 MJPEG {robot_id}: "
                              f"{_miss_count} consecutive misses "
                              f"(active_robot={active})")
                time.sleep(0.2)
            print(f"[ui] 📷 MJPEG {robot_id}: generator exited "
                  f"({_yield_count} yields total)")

        return Response(generate(),
                        mimetype="multipart/x-mixed-replace; boundary=frame",
                        headers={"Cache-Control": "no-cache"})

    @app.route("/video_stop", methods=["POST"])
    def video_stop():
        """Stop the video stream — reset the Subscriber partition.

        Without a matching partition, all robots' writers see
        publication_matched_status.current_count == 0 and stop
        rendering.  Zero CPU, zero network.
        """
        client.deselect_video()
        return jsonify({"success": True})

    @app.route("/clear_coverage", methods=["POST"])
    def clear_coverage():
        """Clear accumulated coverage data in the store."""
        store.clear_coverage()
        return jsonify({"success": True})

    @app.route("/ground_texture.jpg")
    def ground_texture():
        """Serve the farmland aerial-photo used as the 2D canvas background."""
        return send_from_directory(
            os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'shared'),
            "field1_map.jpg",
            mimetype="image/jpeg",
        )

    return app


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(
        description="Robot Fleet UI – subscribes to DDS topics and displays live data"
    )
    parser.add_argument(
        "--domain", type=int, default=0,
        help="DDS Domain ID (must match robot nodes and charging stations). Default: 0",
    )
    parser.add_argument(
        "--ui-port", type=int, default=5000,
        help="HTTP port for the dashboard UI  (default: 5000)",
    )
    args = parser.parse_args()

    # Create the state store and DDS client
    store = FleetStateStore(domain_id=args.domain)
    client = DdsFleetClient(store, domain_id=args.domain)

    # Start DDS — creates participant, readers, requester
    client.start()

    # Create and run the Flask app
    app = create_app(store, client)
    print(f"\n  Dashboard → http://localhost:{args.ui_port}\n")
    app.run(host="0.0.0.0", port=args.ui_port, threaded=True)


if __name__ == "__main__":
    main()
