#!/usr/bin/env python3
"""
Robot Node — the hybrid approach: Hybrid DDS Pub-Sub + gRPC Request-Reply

Uses RTI Connext DDS for all pub-sub data flows and gRPC for
request-reply interactions (commands from the UI, charging-station
slot negotiation).

Hybrid architecture:
  • DDS pub-sub: KinematicState (10 Hz), OperationalState (on change),
    Intent (on change), Telemetry (1 Hz), VideoFrame (~5 fps),
    StationStatus (received).
  • gRPC server: RobotCommandServicer (operator commands).
  • gRPC client: ChargingStation stub (slot negotiation with stations).
  • DDS SPDP handles pub-sub discovery — no per-peer connections.
  • Zeroconf (mDNS) discovers charging-station gRPC addresses.
  • Queue monitoring is DDS-driven via StationStatus listener — no
    polling thread needed (unlike the gRPC approach).

Compare with the gRPC approach (Full Mesh gRPC):
  • Pub-sub via DDS instead of 4 × (N−1) per-peer streaming threads.
  • No reconnect loops — DDS handles discovery and failover.
  • Still uses gRPC for commands and charging (familiar request-reply).
  • Thread count: ~10 fixed (7 app + gRPC pool + DDS) vs ~22+ scaling.

Compare with the DDS approach (Pure DDS):
  • gRPC for commands instead of rti.rpc SimpleReplier.
  • gRPC for charging instead of rti.rpc Requester.
  • Adds Zeroconf for gRPC address discovery (DDS SPDP only covers
    pub-sub endpoints, not gRPC server addresses).
  • Same DDS pub-sub performance for data distribution.

Threading model:
  • 1 position-update thread (10 Hz tick loop)
  • 1 kinematic publisher thread (10 Hz)
  • 1 operational publisher thread (on-change check 10 Hz)
  • 1 intent publisher thread (on-change check 10 Hz)
  • 1 telemetry publisher thread (1 Hz)
  • 1 video publisher thread (~5 fps when selected)
  • 1 status-print thread (every 5 s)
  • gRPC ThreadPoolExecutor (~4 workers for command handling)
  • DDS internal threads (pub-sub delivery + listener callbacks)
  → ~10 threads total, fixed regardless of fleet size

Usage:
    python robot_node.py --id tractor1 --grpc-port 50051 [--domain 0]
"""

import rti.connextdds as dds
import rti.idl as idl
import grpc
from concurrent import futures
import time
import threading
import argparse
import random
import math
import os
import sys
from datetime import datetime
from typing import Dict, List, Optional

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'shared'))
from video_renderer import VideoRenderer
from fleet_discovery import FleetDiscovery

# DDS types (generated by rtiddsgen from robot_types.idl)
from robot_types import (
    RobotStatus, RobotIntentType,
    Position, Velocity3, Waypoint as DdsWaypoint,
    KinematicState, OperationalState, Intent, Telemetry, VideoFrame,
    StationStatus, CoveragePoint,
)

# gRPC protobuf stubs (generated from robot.proto)
import robot_pb2
import robot_pb2_grpc


# Convenience set for charge-related intents
_CHARGE_INTENTS = (RobotIntentType.INTENT_CHARGE_QUEUE,
                   RobotIntentType.INTENT_CHARGE_DOCK)


def _ts():
    """Return a compact HH:MM:SS timestamp for log lines."""
    return datetime.now().strftime("%H:%M:%S")


# ═════════════════════════════════════════════════════════════════════════════
# RobotNode — Hybrid DDS + gRPC robot participant
# ═════════════════════════════════════════════════════════════════════════════

class RobotNode:
    """
    A robot node using DDS for pub-sub and gRPC for request-reply.

    Pub-sub topics (DDS):
      KinematicState (10 Hz), OperationalState (on change), Intent (on change),
      Telemetry (1 Hz), VideoFrame (~5 fps, partition-based).

    Commands (gRPC):
      RobotCommandServicer on the gRPC server handles operator commands.

    Charging (gRPC client + DDS monitoring):
      gRPC: RequestSlot → ConfirmSlot → ReleaseSlot (to stations).
      DDS:  StationStatus listener monitors queue rank changes —
            no polling thread needed (unlike the gRPC approach).
    """

    def __init__(self, robot_id: str, grpc_port: int, domain_id: int = 0):
        self.robot_id = robot_id
        self.grpc_port = grpc_port
        self.domain_id = domain_id
        self.running = False

        # ── Robot state ───────────────────────────────────────────────────
        self.position = {"x": random.uniform(0, 100),
                         "y": random.uniform(0, 100), "z": 0.0}
        self.status = RobotStatus.STATUS_MOVING
        self.intent = RobotIntentType.INTENT_FOLLOW_PATH
        self.battery_level = 100.0
        self.goal: Optional[dict] = None
        self.hold_position: Optional[dict] = None
        self.speed = 2.0
        self.heading = 0.0
        self.velocity_x = 0.0
        self.velocity_y = 0.0
        self.velocity_z = 0.0
        self.signal_strength = 95.0

        # Path route — a loop of waypoints the robot cycles through
        self.path_waypoints = self._generate_path_route()
        self.path_index = 0

        # ── Peer tracking (from DDS readers) ──────────────────────────────
        self.other_robots_state: Dict[str, KinematicState] = {}
        self.other_robots_intent: Dict[str, Intent] = {}
        self.other_robots_operational: Dict[str, OperationalState] = {}
        self._nearby_peers: set = set()

        # ── Charging state (gRPC-based, like the gRPC approach) ───────────────────
        self._charging_station_addresses: List[str] = []  # ["host:port", …]
        self._charging_station_docks: Dict[str, dict] = {}  # addr → {"x","y","station_id"}
        self._charge_slot_id: Optional[str] = None
        self._charge_station_id: Optional[str] = None
        self._charge_station_address: Optional[str] = None  # gRPC address
        self._charge_dock: Optional[dict] = None
        self._charge_wait_pos: Optional[dict] = None
        self._charge_queue_rank: int = -1
        self._charge_requested: bool = False
        self._pre_charge_intent: Optional[RobotIntentType] = None
        self._pre_charge_status: Optional[RobotStatus] = None
        self._pre_charge_speed: float = 2.0
        self._pre_charge_goal: Optional[dict] = None
        self._pre_charge_hold: Optional[dict] = None
        # Station dock positions also learned from DDS StationStatus topic
        self._station_docks: Dict[str, dict] = {}  # station_id → {"x","y","queue_len","is_occupied"}
        self.CHARGE_THRESHOLD = 20.0
        self.CHARGE_FULL = 95.0
        self.CHARGE_RATE = 2.0  # %/s while docked

        # ── Coverage state ─────────────────────────────────────────────────
        self._last_cov_x: float = float('nan')
        self._last_cov_y: float = float('nan')
        self._cov_working: bool = False

        # ── Pre-idle state (saved by CMD_STOP, restored by CMD_RESUME) ────
        self._pre_idle_status: Optional[RobotStatus] = None

        # ── DDS entities ──────────────────────────────────────────────────
        self.participant: Optional[dds.DomainParticipant] = None
        self.writers: Dict[str, dds.DataWriter] = {}
        self.readers: Dict[str, dds.DataReader] = {}

        # ── gRPC server ──────────────────────────────────────────────────
        self.grpc_server = None

        # ── Video rendering ───────────────────────────────────────────────
        self._fleet_robot_ids: List[str] = []
        self.video_renderer = VideoRenderer(robot_id, self._fleet_robot_ids)
        self._video_active = False

        # ── OperationalState change tracking ──────────────────────────────
        self._last_published_status: Optional[RobotStatus] = None
        self._last_published_battery: Optional[float] = None

        # ── Intent change tracking ────────────────────────────────────────
        self._last_published_intent: Optional[RobotIntentType] = None
        self._last_published_target: Optional[tuple] = None
        self._last_published_path_index: Optional[int] = None

        # Locks
        self.data_lock = threading.Lock()

    # ── Path route generation ─────────────────────────────────────────────

    def _generate_path_route(self) -> List[dict]:
        """Generate a path route — a loop of waypoints covering an area."""
        seed = hash(self.robot_id) & 0xFFFFFFFF
        rng = random.Random(seed)
        cx = rng.uniform(20, 80)
        cy = rng.uniform(20, 80)
        radius = rng.uniform(15, 30)
        n_pts = rng.randint(5, 8)
        waypoints = []
        for i in range(n_pts):
            angle = 2 * math.pi * i / n_pts
            jx = rng.uniform(-5, 5)
            jy = rng.uniform(-5, 5)
            wx = max(5, min(95, cx + radius * math.cos(angle) + jx))
            wy = max(5, min(95, cy + radius * math.sin(angle) + jy))
            waypoints.append({"x": wx, "y": wy})
        return waypoints

    @property
    def path_target(self):
        """The waypoint the robot is currently heading toward."""
        return self.path_waypoints[self.path_index]

    # ═════════════════════════════════════════════════════════════════════
    # DDS initialisation (pub-sub only — no RPC entities)
    # ═════════════════════════════════════════════════════════════════════

    def initialize_dds(self):
        """Create the DDS DomainParticipant, pub-sub writers, and readers.

        Unlike the DDS approach, there is NO SimpleReplier for commands and NO
        Requesters for charging — those use gRPC in this hybrid approach.

        Pub-sub: 5 writers (kinematic, operational, intent, telemetry, video)
                 + 4 readers (kinematic, operational, intent, station) with listeners.
        """
        print(f"[{self.robot_id} {_ts()}] Initializing DDS on domain {self.domain_id}...")

        script_dir = os.path.dirname(os.path.abspath(__file__))
        qos_xml = os.path.join(script_dir, "robot_qos.xml")
        qos_provider = dds.QosProvider(qos_xml)

        self.participant = dds.DomainParticipant(self.domain_id)

        # ── Topics ────────────────────────────────────────────────────────
        kin_topic     = dds.Topic(self.participant, "KinematicState",   KinematicState)
        op_topic      = dds.Topic(self.participant, "OperationalState", OperationalState)
        intent_topic  = dds.Topic(self.participant, "Intent",           Intent)
        telem_topic   = dds.Topic(self.participant, "Telemetry",        Telemetry)
        video_topic   = dds.Topic(self.participant, "VideoFrame",       VideoFrame)
        station_topic = dds.Topic(self.participant, "StationStatus",    StationStatus)
        cov_topic     = dds.Topic(self.participant, "CoveragePoint",    CoveragePoint)

        publisher  = dds.Publisher(self.participant)
        subscriber = dds.Subscriber(self.participant)

        # ── Writers (5) ───────────────────────────────────────────────────
        kin_w_qos = qos_provider.datawriter_qos_from_profile(
            "RobotQosLibrary::KinematicStateProfile")
        op_w_qos = qos_provider.datawriter_qos_from_profile(
            "RobotQosLibrary::OperationalStateProfile")
        intent_w_qos = qos_provider.datawriter_qos_from_profile(
            "RobotQosLibrary::IntentProfile")
        telem_w_qos = qos_provider.datawriter_qos_from_profile(
            "RobotQosLibrary::TelemetryProfile")
        video_w_qos = qos_provider.datawriter_qos_from_profile(
            "RobotQosLibrary::VideoProfile")
        cov_w_qos = qos_provider.datawriter_qos_from_profile(
            "RobotQosLibrary::CoverageProfile")

        self.writers['kinematic']   = dds.DataWriter(publisher, kin_topic,    kin_w_qos)
        self.writers['operational'] = dds.DataWriter(publisher, op_topic,     op_w_qos)
        self.writers['intent']      = dds.DataWriter(publisher, intent_topic, intent_w_qos)
        self.writers['telemetry']   = dds.DataWriter(publisher, telem_topic,  telem_w_qos)
        self.writers['coverage']    = dds.DataWriter(publisher, cov_topic,    cov_w_qos)

        # Video DataWriter on a dedicated Publisher with partition
        video_pub_qos = dds.PublisherQos()
        video_pub_qos.partition.name = [self.robot_id]
        video_publisher = dds.Publisher(self.participant, video_pub_qos)
        self.writers['video'] = dds.DataWriter(
            video_publisher, video_topic, video_w_qos)

        # ── Readers (4) ──────────────────────────────────────────────────
        kin_r_qos = qos_provider.datareader_qos_from_profile(
            "RobotQosLibrary::KinematicStateProfile")
        op_r_qos = qos_provider.datareader_qos_from_profile(
            "RobotQosLibrary::OperationalStateProfile")
        intent_r_qos = qos_provider.datareader_qos_from_profile(
            "RobotQosLibrary::IntentProfile")
        station_r_qos = qos_provider.datareader_qos_from_profile(
            "RobotQosLibrary::StationStatusProfile")

        self.readers['kinematic']   = dds.DataReader(subscriber, kin_topic,    kin_r_qos)
        self.readers['operational'] = dds.DataReader(subscriber, op_topic,     op_r_qos)
        self.readers['intent']      = dds.DataReader(subscriber, intent_topic, intent_r_qos)
        self.readers['station']     = dds.DataReader(subscriber, station_topic, station_r_qos)

        # ── Listeners ─────────────────────────────────────────────────────
        self._setup_listeners()

        print(f"[{self.robot_id} {_ts()}] DDS initialized — "
              f"5 writers + 4 readers (pub-sub only, commands via gRPC)")

    # ═════════════════════════════════════════════════════════════════════
    # gRPC server (command handling)
    # ═════════════════════════════════════════════════════════════════════

    def start_grpc_server(self):
        """Start the gRPC server for receiving operator commands.

        Unlike the gRPC approach, this server only hosts RobotCommandServicer —
        there is no RobotStreamingServicer because all data distribution
        is handled by DDS pub-sub.

        Compare with the DDS approach: the DDS approach uses rti.rpc.SimpleReplier
        for command handling.  The hybrid uses gRPC instead.
        """
        self.grpc_server = grpc.server(
            futures.ThreadPoolExecutor(max_workers=4))
        robot_pb2_grpc.add_RobotCommandServicer_to_server(
            RobotCommandServicer(self), self.grpc_server)
        self.grpc_server.add_insecure_port(f'[::]:{self.grpc_port}')
        self.grpc_server.start()
        print(f"[{self.robot_id} {_ts()}] gRPC command server on port {self.grpc_port}")

    # ═════════════════════════════════════════════════════════════════════
    # DDS Listeners — callbacks for received pub-sub data
    # ═════════════════════════════════════════════════════════════════════

    def _setup_listeners(self):
        """Attach DDS DataReaderListeners for pub-sub data reception.

        Identical to the DDS approach — DDS delivers callbacks automatically
        for every matched writer in the domain.  No per-peer connections.
        """
        robot = self

        class KinematicListener(dds.DataReaderListener):
            def on_data_available(self, reader):
                for sample in reader.take():
                    if sample.info.valid:
                        data = sample.data
                        if data.robot_id != robot.robot_id:
                            with robot.data_lock:
                                robot.other_robots_state[data.robot_id] = data

            def on_liveliness_changed(self, reader, status):
                if status.alive_count_change < 0:
                    print(f"[{robot.robot_id} {_ts()}] ⚠  Robot DEAD "
                          f"(alive={status.alive_count})")
                elif status.alive_count_change > 0:
                    print(f"[{robot.robot_id} {_ts()}] ✓  Robot ALIVE "
                          f"(alive={status.alive_count})")

        self.readers['kinematic'].set_listener(
            KinematicListener(),
            dds.StatusMask.DATA_AVAILABLE | dds.StatusMask.LIVELINESS_CHANGED)

        class OperationalListener(dds.DataReaderListener):
            def on_data_available(self, reader):
                for sample in reader.take():
                    if sample.info.valid:
                        data = sample.data
                        if data.robot_id != robot.robot_id:
                            with robot.data_lock:
                                robot.other_robots_operational[data.robot_id] = data

        self.readers['operational'].set_listener(
            OperationalListener(), dds.StatusMask.DATA_AVAILABLE)

        class IntentListener(dds.DataReaderListener):
            def on_data_available(self, reader):
                for sample in reader.take():
                    if sample.info.valid:
                        data = sample.data
                        if data.robot_id != robot.robot_id:
                            with robot.data_lock:
                                robot.other_robots_intent[data.robot_id] = data

        self.readers['intent'].set_listener(
            IntentListener(), dds.StatusMask.DATA_AVAILABLE)

        # StationStatus listener: learn dock positions + monitor charge queue
        class StationStatusListener(dds.DataReaderListener):
            def on_data_available(self, reader):
                for sample in reader.take():
                    if sample.info.valid:
                        data = sample.data
                        with robot.data_lock:
                            robot._station_docks[data.station_id] = {
                                "x": data.dock_x,
                                "y": data.dock_y,
                                "queue_len": len(data.queue),
                                "is_occupied": data.is_occupied,
                            }
                        # Queue monitoring (outside lock — may trigger
                        # RPC calls in _abort_charge).
                        if (robot._charge_station_id == data.station_id
                                and robot.intent in _CHARGE_INTENTS):
                            robot._on_station_status_update(data)

        self.readers['station'].set_listener(
            StationStatusListener(), dds.StatusMask.DATA_AVAILABLE)

    # ═════════════════════════════════════════════════════════════════════
    # Command handling (called from gRPC servicer)
    # ═════════════════════════════════════════════════════════════════════

    def handle_command(self, request) -> robot_pb2.CommandResponse:
        """Process an incoming gRPC command and return a response.

        Called by RobotCommandServicer.SendCommand for each incoming
        CommandRequest.  The logic is identical to the DDS approach's
        _handle_command() but works with protobuf types instead of
        DDS IDL types.
        """
        # Filter: only process commands addressed to this robot
        if request.robot_id != self.robot_id:
            return robot_pb2.CommandResponse(
                success=True,
                description="not addressed to me",
                resulting_status=robot_pb2.RobotStatus.Value(self.status.name),
                resulting_intent=robot_pb2.RobotIntent.Value(self.intent.name),
            )

        cmd_name = robot_pb2.Command.Name(request.command)
        print(f"[{self.robot_id} {_ts()}] Received command: {cmd_name}")

        if request.command == robot_pb2.CMD_STOP:
            # Save current status so RESUME can restore it
            self._pre_idle_status = self.status
            self.status = RobotStatus.STATUS_IDLE
            self.velocity_x = 0.0
            self.velocity_y = 0.0
            desc = "Idle (paused)"

        elif request.command == robot_pb2.CMD_FOLLOW_PATH:
            if self._charge_slot_id:
                self._abort_charge()
            self.goal = None
            self.hold_position = None
            self.intent = RobotIntentType.INTENT_FOLLOW_PATH
            self.status = RobotStatus.STATUS_MOVING
            self._cov_working = False
            self._last_cov_x = float('nan')
            self._last_cov_y = float('nan')
            if request.HasField("goto_params") and request.goto_params.speed > 0:
                self.speed = request.goto_params.speed
            desc = f"Following path at speed {self.speed:.1f}"

        elif request.command == robot_pb2.CMD_GOTO:
            if self._charge_slot_id:
                self._abort_charge()
            gp = request.goto_params
            gx = gp.x
            gy = gp.y
            spd = gp.speed if gp.speed > 0 else 2.0
            self.goal = {"x": gx, "y": gy}
            self.hold_position = None
            self.speed = spd
            self.intent = RobotIntentType.INTENT_GOTO
            self.status = RobotStatus.STATUS_MOVING
            desc = f"Moving to ({gx:.0f}, {gy:.0f}) at speed {spd:.1f}"

        elif request.command == robot_pb2.CMD_RESUME:
            if request.HasField("goto_params") and request.goto_params.speed > 0:
                self.speed = request.goto_params.speed
            if self._pre_idle_status is not None:
                # Restore whatever status we had before STOP
                self.status = self._pre_idle_status
                self._pre_idle_status = None
            elif self.intent == RobotIntentType.INTENT_FOLLOW_PATH:
                self.hold_position = None
                self.status = RobotStatus.STATUS_MOVING
            elif self.intent == RobotIntentType.INTENT_GOTO:
                if self.goal is not None:
                    self.hold_position = None
                    self.status = RobotStatus.STATUS_MOVING
                elif self.hold_position is not None:
                    self.goal = dict(self.hold_position)
                    self.hold_position = None
                    self.status = RobotStatus.STATUS_MOVING
                else:
                    self.hold_position = {
                        "x": self.position["x"],
                        "y": self.position["y"],
                    }
                    self.status = RobotStatus.STATUS_HOLDING
            elif self.intent in _CHARGE_INTENTS:
                if self.goal is not None:
                    self.status = RobotStatus.STATUS_MOVING
                elif self.hold_position is not None:
                    self.status = RobotStatus.STATUS_HOLDING
                else:
                    self.status = RobotStatus.STATUS_MOVING
            else:
                self.hold_position = {
                    "x": self.position["x"],
                    "y": self.position["y"],
                }
                self.status = RobotStatus.STATUS_HOLDING
            desc = f"Resumed ({self.intent.name}) at speed {self.speed:.1f}"

        elif request.command == robot_pb2.CMD_SET_PATH:
            wps = [{"x": wp.x, "y": wp.y}
                   for wp in request.set_path_params.waypoints]
            if len(wps) < 2:
                return robot_pb2.CommandResponse(
                    success=False, description="Need at least 2 waypoints")
            self.path_waypoints = wps
            self.path_index = self.path_index % len(wps)
            desc = f"Path route set ({len(wps)} waypoints)"

        elif request.command == robot_pb2.CMD_CHARGE:
            if not self._charging_station_addresses:
                return robot_pb2.CommandResponse(
                    success=False, description="No charging stations registered")
            if self.status == RobotStatus.STATUS_CHARGING:
                return robot_pb2.CommandResponse(
                    success=False, description="Already charging")
            if self._charge_requested:
                return robot_pb2.CommandResponse(
                    success=False, description="Charge already in progress")
            self._charge_requested = True
            threading.Thread(target=self._initiate_charge, daemon=True).start()
            desc = "Heading to charging station"

        else:
            return robot_pb2.CommandResponse(
                success=False, description=f"Unknown command: {cmd_name}")

        print(f"[{self.robot_id} {_ts()}] → {desc}")
        return robot_pb2.CommandResponse(
            success=True,
            description=desc,
            resulting_status=robot_pb2.RobotStatus.Value(self.status.name),
            resulting_intent=robot_pb2.RobotIntent.Value(self.intent.name),
        )

    # ═════════════════════════════════════════════════════════════════════
    # Charging station interaction (gRPC client + DDS monitoring)
    # ═════════════════════════════════════════════════════════════════════

    def register_charging_station(self, address: str):
        """Record a charging station gRPC address and probe for dock position.

        Called when Zeroconf/mDNS discovers a charging station.  The dock
        position is also learned from DDS StationStatus for ongoing
        monitoring, but the initial gRPC probe provides immediate coords
        and validates the gRPC channel.

        Compare with the DDS approach: no gRPC probing needed — DDS SPDP
        discovers stations and StationStatus (TRANSIENT_LOCAL) delivers
        dock coordinates automatically.
        """
        self._charging_station_addresses.append(address)
        print(f"[{self.robot_id} {_ts()}] Registered charging station at {address}")
        threading.Thread(target=self._probe_station_dock, args=(address,),
                         daemon=True).start()

    def _probe_station_dock(self, address: str):
        """Send an info-only gRPC RequestSlot to learn station dock position."""
        try:
            channel = grpc.insecure_channel(address)
            grpc.channel_ready_future(channel).result(timeout=5)
            stub = robot_pb2_grpc.ChargingStationStub(channel)
            offer = stub.RequestSlot(
                robot_pb2.SlotRequest(
                    robot_id=self.robot_id,
                    battery_level=100.0,
                    info_only=True,
                ),
                timeout=5,
            )
            channel.close()
            self._charging_station_docks[address] = {
                "x": offer.dock_x,
                "y": offer.dock_y,
                "station_id": offer.station_id,
            }
            print(f"[{self.robot_id} {_ts()}] Probed station {offer.station_id} "
                  f"dock=({offer.dock_x:.0f},{offer.dock_y:.0f})")
        except Exception as e:
            print(f"[{self.robot_id} {_ts()}] Station probe failed at {address}: {e}")

    def _initiate_charge(self):
        """Begin the charging workflow via gRPC.

        Iterates over all known charging station addresses, opens a gRPC
        channel to each, collects offers, picks the best, confirms the
        slot, and navigates to the station.

        Queue monitoring is DDS-driven via the StationStatus listener —
        no polling thread needed (unlike the gRPC approach's _poll_charge_queue).

        Compare with the DDS approach: the DDS approach sends one DDS request that
        fans out to all stations via multicast.  The hybrid opens one
        gRPC channel per station.
        """
        if self.intent in _CHARGE_INTENTS:
            self._charge_requested = False
            return

        # Stash current state
        self._pre_charge_intent = self.intent
        self._pre_charge_status = self.status
        self._pre_charge_speed = self.speed
        self._pre_charge_goal = dict(self.goal) if self.goal else None
        self._pre_charge_hold = dict(self.hold_position) if self.hold_position else None
        self._cov_working = False  # stop recording during charge cycle

        print(f"[{self.robot_id} {_ts()}] ⚡ Battery {self.battery_level:.0f}% — requesting charge slot")

        # Fan out RequestSlot to all known stations via gRPC
        offers: list[tuple] = []  # (offer, address)
        for addr in self._charging_station_addresses:
            try:
                channel = grpc.insecure_channel(addr)
                grpc.channel_ready_future(channel).result(timeout=3)
                stub = robot_pb2_grpc.ChargingStationStub(channel)
                offer = stub.RequestSlot(
                    robot_pb2.SlotRequest(
                        robot_id=self.robot_id,
                        battery_level=self.battery_level,
                    ),
                    timeout=5,
                )
                channel.close()
                offers.append((offer, addr))
            except Exception as e:
                print(f"[{self.robot_id} {_ts()}] Failed to reach station at {addr}: {e}")

        if not offers:
            print(f"[{self.robot_id} {_ts()}] ✗ No charging station reachable — staying on task")
            self._charge_requested = False
            return

        # Pick best offer (shortest wait, then closest)
        def _score(t):
            offer = t[0]
            dx = offer.dock_x - self.position["x"]
            dy = offer.dock_y - self.position["y"]
            dist = math.sqrt(dx * dx + dy * dy)
            return (offer.wait_time_s, dist)

        offers.sort(key=_score)
        best_offer, best_address = offers[0]
        rejected = offers[1:]

        # Release rejected offers
        for rej_offer, rej_addr in rejected:
            try:
                ch = grpc.insecure_channel(rej_addr)
                grpc.channel_ready_future(ch).result(timeout=2)
                st = robot_pb2_grpc.ChargingStationStub(ch)
                st.ReleaseSlot(robot_pb2.SlotRelease(
                    robot_id=self.robot_id,
                    slot_id=rej_offer.slot_id,
                ), timeout=3)
                ch.close()
            except Exception:
                pass

        # Confirm the best slot via gRPC
        try:
            channel = grpc.insecure_channel(best_address)
            grpc.channel_ready_future(channel).result(timeout=3)
            stub = robot_pb2_grpc.ChargingStationStub(channel)
            assignment = stub.ConfirmSlot(
                robot_pb2.SlotConfirm(
                    robot_id=self.robot_id,
                    slot_id=best_offer.slot_id,
                ),
                timeout=5,
            )
            channel.close()
        except Exception as e:
            print(f"[{self.robot_id} {_ts()}] ✗ Failed to confirm slot: {e}")
            self._charge_requested = False
            return

        if not assignment.granted:
            print(f"[{self.robot_id} {_ts()}] ✗ Slot not granted")
            self._charge_requested = False
            return

        # Guard against a command that changed intent while we were
        # waiting for the gRPC round-trips (e.g. rapid CHARGE → GOTO).
        if self.intent not in (self._pre_charge_intent, *_CHARGE_INTENTS):
            print(f"[{self.robot_id} {_ts()}] ⚡ Intent changed to "
                  f"{self.intent.name} during reserve — releasing slot")
            try:
                channel = grpc.insecure_channel(best_address)
                grpc.channel_ready_future(channel).result(timeout=2)
                stub = robot_pb2_grpc.ChargingStationStub(channel)
                stub.ReleaseSlot(robot_pb2.SlotRelease(
                    robot_id=self.robot_id,
                    slot_id=best_offer.slot_id,
                ), timeout=3)
                channel.close()
            except Exception:
                pass
            self._charge_requested = False
            return

        # Store charge state
        self._charge_slot_id = best_offer.slot_id
        self._charge_station_id = best_offer.station_id
        self._charge_dock = {"x": assignment.dock_x, "y": assignment.dock_y}
        self._charge_wait_pos = {"x": assignment.wait_x, "y": assignment.wait_y}
        self._charge_queue_rank = assignment.queue_rank
        self._charge_station_address = best_address

        # Navigate to the station
        if assignment.queue_rank == 0:
            self.goal = dict(self._charge_dock)
            self.intent = RobotIntentType.INTENT_CHARGE_DOCK
            print(f"[{self.robot_id} {_ts()}] ⚡ Heading to dock "
                  f"({self.goal['x']:.0f},{self.goal['y']:.0f})")
        else:
            self.goal = dict(self._charge_wait_pos)
            self.intent = RobotIntentType.INTENT_CHARGE_QUEUE
            print(f"[{self.robot_id} {_ts()}] ⚡ Heading to wait position "
                  f"rank={assignment.queue_rank}")

        self.status = RobotStatus.STATUS_MOVING
        self.hold_position = None
        self.speed = 3.0

        # NOTE: No polling thread spawned here (unlike the gRPC approach).
        # Queue-rank monitoring is handled by the DDS StationStatus
        # listener — _on_station_status_update() fires whenever the
        # station publishes an updated queue.

    def _on_station_status_update(self, status: StationStatus):
        """React to a DDS StationStatus update for our charging station.

        Called from StationStatusListener when the station publishes
        an updated queue.  This replaces the gRPC approach's _poll_charge_queue
        thread — DDS pub-sub delivers queue changes automatically.

        If our rank dropped to 0 → navigate to dock.
        If our rank changed → update wait position.
        If we disappeared from queue → abort charge.
        """
        if not self._charge_slot_id:
            return

        my_rank = -1
        for entry in status.queue:
            if entry.robot_id == self.robot_id:
                my_rank = entry.rank
                break

        if my_rank < 0:
            if self.intent == RobotIntentType.INTENT_CHARGE_QUEUE:
                print(f"[{self.robot_id} {_ts()}] ⚡ Disappeared from "
                      f"{status.station_id} queue — aborting charge")
                self._abort_charge()
                self.intent = self._pre_charge_intent or RobotIntentType.INTENT_FOLLOW_PATH
                self.status = RobotStatus.STATUS_MOVING
                self.speed = self._pre_charge_speed
                self.goal = self._pre_charge_goal
                self.hold_position = None
            return

        old_rank = self._charge_queue_rank
        self._charge_queue_rank = my_rank

        if my_rank == 0 and old_rank != 0:
            self.goal = dict(self._charge_dock)
            self.hold_position = None
            self.intent = RobotIntentType.INTENT_CHARGE_DOCK
            self.status = RobotStatus.STATUS_MOVING
            print(f"[{self.robot_id} {_ts()}] ⚡ Queue advanced → heading to dock")
        elif my_rank != old_rank and my_rank > 0:
            wx, wy = self._wait_position(
                self._charge_dock["x"], self._charge_dock["y"], my_rank)
            self._charge_wait_pos = {"x": wx, "y": wy}
            self.goal = dict(self._charge_wait_pos)
            self.hold_position = None
            self.status = RobotStatus.STATUS_MOVING
            print(f"[{self.robot_id} {_ts()}] ⚡ Queue rank {old_rank} → {my_rank}")

    @staticmethod
    def _wait_position(dock_x: float, dock_y: float, rank: int) -> tuple:
        """Compute a waiting position near a station for a given queue rank."""
        spacing = 8
        offset = 10 + rank * spacing
        dx = 1 if dock_x < 50 else -1
        dy = 1 if dock_y < 50 else -1
        if abs(50 - dock_x) >= abs(50 - dock_y):
            return (dock_x + dx * offset, dock_y)
        else:
            return (dock_x, dock_y + dy * offset)

    def _abort_charge(self):
        """Cancel an in-progress charge via gRPC ReleaseSlot.

        Fire-and-forget: the gRPC release runs in a background thread
        so we never block the DDS listener or command handler thread.
        """
        if self._charge_slot_id and self._charge_station_address:
            slot_id = self._charge_slot_id
            station_addr = self._charge_station_address
            robot_id = self.robot_id
            def _do_release():
                try:
                    channel = grpc.insecure_channel(station_addr)
                    grpc.channel_ready_future(channel).result(timeout=3)
                    stub = robot_pb2_grpc.ChargingStationStub(channel)
                    stub.ReleaseSlot(
                        robot_pb2.SlotRelease(
                            robot_id=robot_id,
                            slot_id=slot_id,
                        ),
                        timeout=5,
                    )
                    channel.close()
                except Exception:
                    pass
            threading.Thread(target=_do_release, daemon=True).start()
            print(f"[{self.robot_id} {_ts()}] ⚡ Charge aborted (slot released)")
        self._clear_charge_state()

    def _release_charge_slot(self):
        """Release the slot at the charging station and resume prior task.

        Fire-and-forget like _abort_charge — called from the
        update_position thread; blocking it pauses the simulation.
        """
        if self._charge_slot_id and self._charge_station_address:
            slot_id = self._charge_slot_id
            station_addr = self._charge_station_address
            robot_id = self.robot_id
            def _do_release():
                try:
                    channel = grpc.insecure_channel(station_addr)
                    grpc.channel_ready_future(channel).result(timeout=3)
                    stub = robot_pb2_grpc.ChargingStationStub(channel)
                    stub.ReleaseSlot(
                        robot_pb2.SlotRelease(
                            robot_id=robot_id,
                            slot_id=slot_id,
                        ),
                        timeout=5,
                    )
                    channel.close()
                except Exception:
                    pass
            threading.Thread(target=_do_release, daemon=True).start()

        print(f"[{self.robot_id} {_ts()}] ⚡ Charging complete "
              f"({self.battery_level:.0f}%) — resuming")

        # Restore pre-charge state
        if (self._pre_charge_intent == RobotIntentType.INTENT_GOTO
                and self._pre_charge_goal is None
                and self._pre_charge_hold is not None):
            self.intent = RobotIntentType.INTENT_GOTO
            self.goal = dict(self._pre_charge_hold)
            self.hold_position = None
            self.status = RobotStatus.STATUS_MOVING
            self.speed = self._pre_charge_speed
        else:
            self.intent = self._pre_charge_intent or RobotIntentType.INTENT_FOLLOW_PATH
            self.status = RobotStatus.STATUS_MOVING
            self.speed = self._pre_charge_speed
            self.goal = self._pre_charge_goal
            self.hold_position = None

        self._clear_charge_state()

    def _clear_charge_state(self):
        """Reset all charge-related fields."""
        self._charge_slot_id = None
        self._charge_station_id = None
        self._charge_station_address = None
        self._charge_dock = None
        self._charge_wait_pos = None
        self._charge_queue_rank = -1
        self._charge_requested = False
        self._cov_working = False
        self._last_cov_x = float('nan')
        self._last_cov_y = float('nan')
        self._pre_charge_intent = None
        self._pre_charge_status = None
        self._pre_charge_speed = 2.0
        self._pre_charge_goal = None
        self._pre_charge_hold = None

    # ═════════════════════════════════════════════════════════════════════
    # Collision avoidance
    # ═════════════════════════════════════════════════════════════════════

    AVOIDANCE_RADIUS = 12.0
    AVOIDANCE_STRENGTH = 4.0
    MIN_SEPARATION = 4.0

    @property
    def _is_docking(self) -> bool:
        return (self.intent == RobotIntentType.INTENT_CHARGE_DOCK
                and self.goal is not None)

    def _compute_avoidance(self):
        """Return (dx, dy, hard_override) repulsion from nearby peers."""
        ax, ay = 0.0, 0.0
        hard_override = False
        mx, my = self.position["x"], self.position["y"]
        docking = self._is_docking
        near_station = (self.intent in _CHARGE_INTENTS
                        and self._charge_dock is not None)

        if docking:
            eff_radius = self.AVOIDANCE_RADIUS * 0.4
            eff_strength = self.AVOIDANCE_STRENGTH * 0.3
        elif near_station:
            eff_radius = self.AVOIDANCE_RADIUS * 0.5
            eff_strength = self.AVOIDANCE_STRENGTH * 0.25
        else:
            eff_radius = self.AVOIDANCE_RADIUS
            eff_strength = self.AVOIDANCE_STRENGTH

        with self.data_lock:
            peers = {
                rid: (s.position.x, s.position.y)
                for rid, s in self.other_robots_state.items()
                if rid != self.robot_id
            }
            docking_peers: set = set()
            if near_station and not docking:
                for rid in peers:
                    intent_msg = self.other_robots_intent.get(rid)
                    if (intent_msg
                            and intent_msg.intent_type == RobotIntentType.INTENT_CHARGE_DOCK):
                        docking_peers.add(rid)

        for rid, (px, py) in peers.items():
            dx = mx - px
            dy = my - py
            dist = math.sqrt(dx * dx + dy * dy)

            was_nearby = rid in self._nearby_peers
            is_nearby = dist < eff_radius
            # Hysteresis: enter at eff_radius, clear at 115% to avoid
            # log flicker when peers hover near the boundary.
            is_clear = dist > eff_radius * 1.15

            if is_nearby and not was_nearby:
                print(f"[{self.robot_id} {_ts()}] ⚠ Peer {rid} nearby "
                      f"({dist:.1f} units) — avoiding")
                self._nearby_peers.add(rid)
            elif is_clear and was_nearby:
                print(f"[{self.robot_id} {_ts()}] ✓ Peer {rid} clear "
                      f"({dist:.1f} units)")
                self._nearby_peers.discard(rid)

            if is_nearby and dist > 0.01:
                ratio = eff_radius / dist
                strength = eff_strength * ratio * ratio
                if near_station and rid in docking_peers:
                    strength *= 3.0
                ax += (dx / dist) * strength
                ay += (dy / dist) * strength
                if dist < self.MIN_SEPARATION and not near_station and not docking:
                    hard_override = True

        return ax, ay, hard_override

    # ═════════════════════════════════════════════════════════════════════
    # Position update (movement tick)
    # ═════════════════════════════════════════════════════════════════════

    def update_position(self):
        """Simulate robot movement — 10 Hz tick loop."""
        dt = 0.1
        while self.running:
            if self.status == RobotStatus.STATUS_MOVING:
                vx, vy = 0.0, 0.0

                if (self.intent in (RobotIntentType.INTENT_GOTO, *_CHARGE_INTENTS)
                        and self.goal is not None):
                    dx = self.goal["x"] - self.position["x"]
                    dy = self.goal["y"] - self.position["y"]
                    dist = (dx**2 + dy**2) ** 0.5

                    if dist <= self.speed * dt:
                        self.position["x"] = self.goal["x"]
                        self.position["y"] = self.goal["y"]
                        if dist > 0.01:
                            self.heading = math.atan2(dy, dx)
                        self.velocity_x = 0.0
                        self.velocity_y = 0.0

                        if self.intent == RobotIntentType.INTENT_CHARGE_DOCK:
                            print(f"[{self.robot_id} {_ts()}] Arrived at charging dock → CHARGING")
                            self.goal = None
                            self.status = RobotStatus.STATUS_CHARGING
                        elif self.intent == RobotIntentType.INTENT_CHARGE_QUEUE:
                            print(f"[{self.robot_id} {_ts()}] Arrived at charge wait pos "
                                  f"(rank {self._charge_queue_rank})")
                            self.hold_position = {"x": self.goal["x"], "y": self.goal["y"]}
                            self.goal = None
                            self.status = RobotStatus.STATUS_HOLDING
                        else:
                            print(f"[{self.robot_id} {_ts()}] Reached goal "
                                  f"({self.goal['x']:.1f}, {self.goal['y']:.1f}) → HOLDING")
                            self.hold_position = {"x": self.goal["x"], "y": self.goal["y"]}
                            self.goal = None
                            self.status = RobotStatus.STATUS_HOLDING
                    else:
                        vx = dx / dist * self.speed
                        vy = dy / dist * self.speed

                elif self.intent == RobotIntentType.INTENT_FOLLOW_PATH:
                    wp = self.path_target
                    dx = wp["x"] - self.position["x"]
                    dy = wp["y"] - self.position["y"]
                    dist = (dx**2 + dy**2) ** 0.5

                    if dist <= self.speed * dt:
                        self.position["x"] = wp["x"]
                        self.position["y"] = wp["y"]
                        self.path_index = (self.path_index + 1) % len(self.path_waypoints)
                        self._cov_working = True  # reached a waypoint — coverage starts
                        nwp = self.path_target
                        ndx = nwp["x"] - self.position["x"]
                        ndy = nwp["y"] - self.position["y"]
                        ndist = (ndx**2 + ndy**2) ** 0.5
                        if ndist > 0.01:
                            vx = ndx / ndist * self.speed
                            vy = ndy / ndist * self.speed
                    else:
                        vx = dx / dist * self.speed
                        vy = dy / dist * self.speed

                if self.status == RobotStatus.STATUS_MOVING:
                    avoid_x, avoid_y, hard_override = self._compute_avoidance()
                    if hard_override:
                        vx, vy = avoid_x, avoid_y
                    else:
                        vx += avoid_x
                        vy += avoid_y

                    self.position["x"] += vx * dt
                    self.position["y"] += vy * dt
                    self.velocity_x = vx
                    self.velocity_y = vy
                    if abs(vx) + abs(vy) > 0.01:
                        self.heading = math.atan2(vy, vx)

                    # ── Coverage point (active path work only) ────────
                    if self.intent == RobotIntentType.INTENT_FOLLOW_PATH:
                        if self._cov_working and not self._charge_requested:
                            cx, cy = self.position["x"], self.position["y"]
                            dx_c = cx - self._last_cov_x
                            dy_c = cy - self._last_cov_y
                            if not (dx_c * dx_c + dy_c * dy_c < 1.0):
                                self.writers['coverage'].write(CoveragePoint(
                                    robot_id=self.robot_id,
                                    x=cx, y=cy))
                                self._last_cov_x = cx
                                self._last_cov_y = cy

            elif self.status == RobotStatus.STATUS_HOLDING:
                vx, vy = 0.0, 0.0
                if self.hold_position:
                    dx = self.hold_position["x"] - self.position["x"]
                    dy = self.hold_position["y"] - self.position["y"]
                    dist = math.sqrt(dx * dx + dy * dy)
                    if dist > 0.05:
                        spring_speed = min(0.5, dist)
                        vx = dx / dist * spring_speed
                        vy = dy / dist * spring_speed

                avoid_x, avoid_y, hard_override = self._compute_avoidance()
                if hard_override:
                    vx, vy = avoid_x, avoid_y
                else:
                    vx += avoid_x
                    vy += avoid_y

                self.position["x"] += vx * dt
                self.position["y"] += vy * dt
                self.velocity_x = vx
                self.velocity_y = vy
                if abs(vx) + abs(vy) > 0.01:
                    self.heading = math.atan2(vy, vx)

            elif self.status == RobotStatus.STATUS_CHARGING:
                self.velocity_x = 0.0
                self.velocity_y = 0.0
                self.battery_level = min(100.0, self.battery_level + self.CHARGE_RATE * dt)
                if self.battery_level >= self.CHARGE_FULL:
                    self._release_charge_slot()

            # Clamp to arena
            self.position["x"] = max(0, min(100, self.position["x"]))
            self.position["y"] = max(0, min(100, self.position["y"]))

            # Battery drain
            if self.status != RobotStatus.STATUS_CHARGING:
                actual_speed = math.sqrt(self.velocity_x**2 + self.velocity_y**2)
                drain = 0.01 + 0.01 * actual_speed
                self.battery_level = max(0, self.battery_level - drain)

            # Signal strength
            cx = abs(self.position["x"] - 50.0)
            cy = abs(self.position["y"] - 50.0)
            edge_dist = max(cx, cy)
            base_signal = max(10.0, 100.0 - edge_dist * 1.6)
            self.signal_strength = max(0.0, min(100.0,
                base_signal + random.uniform(-3.0, 3.0)))

            # Auto-charge trigger
            if (self.battery_level < self.CHARGE_THRESHOLD
                    and not self._charge_requested
                    and self._charging_station_addresses
                    and self.status != RobotStatus.STATUS_CHARGING):
                self._charge_requested = True
                threading.Thread(target=self._initiate_charge, daemon=True).start()

            time.sleep(dt)

    # ═════════════════════════════════════════════════════════════════════
    # DDS Publishers — periodic data publishing threads
    # ═════════════════════════════════════════════════════════════════════

    def publish_kinematic_state(self):
        """Publish KinematicState at 10 Hz via DDS."""
        while self.running:
            sample = KinematicState(
                robot_id=self.robot_id,
                position=Position(
                    x=self.position['x'],
                    y=self.position['y'],
                    z=self.position['z'],
                ),
                velocity=Velocity3(
                    x=self.velocity_x,
                    y=self.velocity_y,
                    z=self.velocity_z,
                ),
                heading=self.heading,
            )
            self.writers['kinematic'].write(sample)
            time.sleep(0.1)

    def publish_operational_state(self):
        """Publish OperationalState on change via DDS."""
        while self.running:
            current_status = self.status
            current_battery = round(self.battery_level, 1)

            if (current_status != self._last_published_status
                    or current_battery != self._last_published_battery):
                sample = OperationalState(
                    robot_id=self.robot_id,
                    status=current_status,
                    battery_level=self.battery_level,
                )
                self.writers['operational'].write(sample)
                self._last_published_status = current_status
                self._last_published_battery = current_battery

            time.sleep(0.1)

    def publish_intent(self):
        """Publish Intent on change via DDS."""
        while self.running:
            if self.intent == RobotIntentType.INTENT_GOTO:
                if self.goal is not None:
                    tx, ty = self.goal["x"], self.goal["y"]
                elif self.hold_position is not None:
                    tx, ty = self.hold_position["x"], self.hold_position["y"]
                else:
                    tx, ty = self.position["x"], self.position["y"]
            elif self.intent in _CHARGE_INTENTS:
                if self._charge_dock:
                    tx, ty = self._charge_dock["x"], self._charge_dock["y"]
                elif self.goal:
                    tx, ty = self.goal["x"], self.goal["y"]
                else:
                    tx, ty = self.position["x"], self.position["y"]
            elif self.intent == RobotIntentType.INTENT_FOLLOW_PATH:
                wp = self.path_target
                tx, ty = wp["x"], wp["y"]
            else:
                tx, ty = self.position["x"], self.position["y"]

            current_target = (round(tx, 1), round(ty, 1))

            if (self.intent != self._last_published_intent
                    or current_target != self._last_published_target
                    or self.path_index != self._last_published_path_index):

                path_wps = []
                if self.intent == RobotIntentType.INTENT_FOLLOW_PATH:
                    path_wps = [DdsWaypoint(x=w["x"], y=w["y"])
                                for w in self.path_waypoints]

                sample = Intent(
                    robot_id=self.robot_id,
                    intent_type=self.intent,
                    target_position=Position(x=tx, y=ty, z=0.0),
                    path_waypoints=path_wps,
                    path_index=self.path_index,
                )
                self.writers['intent'].write(sample)
                self._last_published_intent = self.intent
                self._last_published_target = current_target
                self._last_published_path_index = self.path_index

            time.sleep(0.1)

    def publish_telemetry(self):
        """Publish Telemetry at 1 Hz via DDS."""
        while self.running:
            sample = Telemetry(
                robot_id=self.robot_id,
                cpu_usage=random.uniform(20, 80),
                memory_usage=random.uniform(30, 70),
                temperature=random.uniform(40, 70),
                signal_strength=self.signal_strength,
            )
            self.writers['telemetry'].write(sample)
            time.sleep(1.0)

    def _is_video_requested(self) -> bool:
        """Check if UI is viewing this robot's camera using partition matching."""
        try:
            return (self.writers['video']
                    .publication_matched_status.current_count > 0)
        except Exception:
            return False

    def publish_video(self):
        """Publish VideoFrame at ~5 fps via DDS — only when selected."""
        was_active = False

        while self.running:
            requested = self._is_video_requested()

            if not requested:
                if was_active:
                    print(f"[{self.robot_id} {_ts()}] 📷 Video: "
                          f"no longer selected — pausing render")
                    was_active = False
                time.sleep(1.0)
                continue

            if not was_active:
                print(f"[{self.robot_id} {_ts()}] 📷 Video: "
                      f"selected by UI — starting render")
                was_active = True

            try:
                with self.data_lock:
                    for rid in self.other_robots_state:
                        if rid not in self._fleet_robot_ids and rid != self.robot_id:
                            self._fleet_robot_ids.append(rid)

                    peers = {}
                    for rid, ks in self.other_robots_state.items():
                        if rid != self.robot_id:
                            os_msg = self.other_robots_operational.get(rid)
                            status_name = (os_msg.status.name
                                           if os_msg else "STATUS_MOVING")
                            peers[rid] = {
                                "x": ks.position.x,
                                "y": ks.position.y,
                                "heading": ks.heading,
                                "status": status_name,
                            }

                    snap_pos = dict(self.position)
                    snap_heading = self.heading
                    snap_wps = list(self.path_waypoints)

                    stations = {}
                    for sid, dock in self._station_docks.items():
                        is_active = (self.status == RobotStatus.STATUS_CHARGING
                                     and self._charge_station_id == sid)
                        stations[sid] = {
                            "x": dock["x"],
                            "y": dock["y"],
                            "active": is_active,
                        }

                jpeg_bytes = self.video_renderer.render_frame(
                    my_pos=snap_pos,
                    my_heading=snap_heading,
                    peers=peers,
                    my_waypoints=snap_wps,
                    charging_stations=stations,
                )

                frame = VideoFrame(
                    robot_id=self.robot_id,
                    frame_data=jpeg_bytes,
                )
                self.writers['video'].write(frame)
            except Exception as e:
                if self.running:
                    print(f"[{self.robot_id} {_ts()}] 📷 Video render error: {e}")

            time.sleep(0.2)

    # ═════════════════════════════════════════════════════════════════════
    # Status reporting
    # ═════════════════════════════════════════════════════════════════════

    def print_status(self):
        """Periodically print a one-line status summary."""
        prev_status = None
        prev_intent = None
        ticks = 0
        while self.running:
            time.sleep(5)
            ticks += 1
            with self.data_lock:
                n_peers = len(self.other_robots_state)
            status_name = self.status.name
            intent_name = self.intent.name
            changed = (status_name != prev_status or intent_name != prev_intent)
            prev_status = status_name
            prev_intent = intent_name
            if not changed and ticks < 6:
                continue
            ticks = 0
            x, y = self.position['x'], self.position['y']
            batt = self.battery_level
            sig = self.signal_strength
            n_stations = len(self._charging_station_addresses)
            print(f"[{self.robot_id} {_ts()}] pos=({x:.1f},{y:.1f}) "
                  f"{status_name}/{intent_name} batt={batt:.0f}% "
                  f"sig={sig:.0f}% peers={n_peers} "
                  f"stations(gRPC)={n_stations}")

    # ═════════════════════════════════════════════════════════════════════
    # Main run loop
    # ═════════════════════════════════════════════════════════════════════

    def run(self):
        """Initialise DDS, start gRPC server, launch threads (non-blocking)."""
        self.initialize_dds()
        self.start_grpc_server()
        self.running = True

        self._threads = [
            threading.Thread(target=self.update_position,          daemon=True, name="position"),
            threading.Thread(target=self.publish_kinematic_state,  daemon=True, name="kinematic"),
            threading.Thread(target=self.publish_operational_state, daemon=True, name="operational"),
            threading.Thread(target=self.publish_intent,           daemon=True, name="intent"),
            threading.Thread(target=self.publish_telemetry,        daemon=True, name="telemetry"),
            threading.Thread(target=self.publish_video,            daemon=True, name="video"),
            threading.Thread(target=self.print_status,             daemon=True, name="status"),
        ]

        for t in self._threads:
            t.start()

        print(f"[{self.robot_id} {_ts()}] Robot is running "
              f"({len(self._threads)} app threads + gRPC pool + DDS internal). "
              f"Press Ctrl+C to stop.")

    def shutdown(self):
        """Stop gRPC server, join threads, close DDS participant."""
        print(f"\n[{self.robot_id} {_ts()}] Shutting down...")
        self.running = False
        self.grpc_server.stop(0)
        for t in self._threads:
            t.join(timeout=1)
        if self.participant:
            self.participant.close()


# ═════════════════════════════════════════════════════════════════════════════
# gRPC Command Servicer
# ═════════════════════════════════════════════════════════════════════════════

class RobotCommandServicer(robot_pb2_grpc.RobotCommandServicer):
    """gRPC unary servicer for operator commands.

    Delegates to RobotNode.handle_command() for the actual logic.

    Compare with the DDS approach: command handling is a SimpleReplier callback
    on DDS internal threads.  Here it runs on the gRPC ThreadPoolExecutor.
    """

    def __init__(self, robot_node: RobotNode):
        self.robot = robot_node

    def SendCommand(self, request, context):
        return self.robot.handle_command(request)


# ═════════════════════════════════════════════════════════════════════════════
# CLI entry point
# ═════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description='Robot Node — the hybrid approach: Hybrid DDS Pub-Sub + gRPC Request-Reply')
    parser.add_argument('--id', required=True, help='Robot ID (e.g. tractor1)')
    parser.add_argument('--grpc-port', type=int, required=True,
                        help='gRPC port for receiving commands')
    parser.add_argument('--domain', type=int, default=0,
                        help='DDS Domain ID (default: 0)')
    parser.add_argument('--same-host', action='store_true',
                        help='All nodes on same machine — use localhost for Zeroconf')
    args = parser.parse_args()

    robot = RobotNode(args.id, args.grpc_port, args.domain)

    # Station discovery callback (Zeroconf → register gRPC address)
    use_localhost = args.same_host

    def _on_station_discovered(address: str):
        host, port_s = address.rsplit(":", 1)
        target = f"localhost:{port_s}" if use_localhost else address
        robot.register_charging_station(target)

    # Start gRPC + DDS + background threads
    robot.run()

    # Start Zeroconf discovery for charging stations (gRPC addresses)
    # Also register this robot's gRPC command port so the UI can find us.
    # NOTE: This must happen AFTER robot.run() returns — but run() starts
    # threads and returns immediately (the main loop is below).
    discovery = FleetDiscovery(
        robot_id=args.id,
        grpc_port=args.grpc_port,
        on_station_added=_on_station_discovered,
    )
    discovery.start()

    try:
        while robot.running:
            time.sleep(1)
    except KeyboardInterrupt:
        pass
    finally:
        robot.shutdown()
        discovery.close()


if __name__ == '__main__':
    main()
